### ISSUE TITLE
Allow users to upload multiple files when contacting us

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#1008]
Related to #913 

When a user is Contacting Us via Terra, give them the ability to attach multiple files. Currently they are limited to one attachment.

Users can add and remove up to X number of files, where they can add and remove multiple files individually.

**Comment by bradtaylor** [comment]
I'm going to close this issue for now, as I suspect otherwise it would linger down at the bottom of the backlog as new usability improvement requests came in
