### ISSUE TITLE
Create a "getting started with Saturn" document

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#101]
Internal stakeholders need a way into the system so they can view progress as it happens. This includes both Broad and Verily staff. We therefore need a brief how-to document that describes the process of getting set up with a Saturn account.

Saturn on-boarding for try-it-out users at present involves registering in FireCloud. From there, Broad/Verily users should email saturn-dev@broadinstitute.org to be given access to try-it-out workspaces. They will also be added to the try-saturn billing project. This allows them to create their own workspaces in FireCloud which can be viewed in Saturn. We should include appropriate warnings to avoid conducting expensive analyses under this billing-project.

Non-Verily/Google users have the option of proceeding to create their own billing-account/project if they wish. Verily customers cannot create billing projects at this time as their security disallows granting the required scope.
 
Acceptance Criteria:
* Document exists and has been approved by Brad Taylor, Geraldine Van der Auwera  and David Glazer
* Document has been placed in the wiki of this repo and referenced from the main repo README.md

**Comment by dmohs** [comment]
Add comments here:
https://docs.google.com/document/d/1xIpzsXJKy3dgOlo5MJmxz3QSVZjOn6oSJS-lwyB76JQ/edit
