### ISSUE TITLE
"Share workspace" dialog: add user pop-up field appears broken

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/saturn-ui#1025]
When attempting to add a user through the "Share Workspace" dialog, I am required to know that I need to hit `Enter` in order for the user to be added to the list. I believe this is because the "add user" field is broken.

To reproduce:

1. Create a workspace
2. Click the "..." menu on the right hand side and select "Share"
3. In the "Share Workspace" dialog where it says "Add people or groups" type: `newuser@somedomain.com`

The first time I do this after opening the dialog, a little field pops up, under where I am typing, and when I have entered a full email address I see to the right a "+" symbol inside a circle.

Bad thing:
Clicking on the "+" symbol does nothing except hide that pop-up field.

Good thing:
Clicking on any other part of the pop-up field adds the user to the list of "Current Collaborators" as a reader.

Good thing:
Hitting enter adds the user `newuser@somedomain.com` to the list of "Current Collaborators" as a Reader.

Bad thing:
Now if I type another username (`anotheruser@somedomain.com`) in the "Add people or groups" field, the validation field does not pop up.

Good thing:
Hitting enter adds the user `anotheruser@somedomain.com` to the list of "Current Collaborators" as a Reader.

**Comment by elizzhao** [comment]
Closed with #1067

**Comment by mbookman** [comment]
For completeness, this was closed via the submission of https://github.com/DataBiosphere/saturn-ui/pull/1080.

Question - was the second "Bad thing" reported above addressed by https://github.com/DataBiosphere/saturn-ui/pull/1080?

**Comment by elizzhao** [comment]
Yes I believe so, the field continues to show up after adding a person

**Comment by mbookman** [comment]
Great. Thanks!
