### ISSUE TITLE
Unable to load notebooks with a colon in the name

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/saturn-ui#1026]
If I create a notebook and include a colon in the name, I then cannot open the notebook.
The UI shows me:

```
Terra is preparing your notebook
- Waiting for notebook runtime to be ready
- Error loading notebook, retry number 5...
```
and the error bar at the top shows details:

```
Notebook cannot be launched
Unable to copy notebook to cluster, was it renamed or deleted in the Workspace Bucket?
```

When I try to set the name of a notebook, I get a warning:

```
NAME CAN'T CONTAIN ANY OF THESE CHARACTERS: "#[]*?"
```

So I assumed that colons are okay.

I was naming my notebooks as:

```
Py3: Getting Started
```

When I rename this to:

```
Py3 - Getting Started
```

the notebook loads fine.

**Comment by mbookman** [comment]
Thanks!

**Comment by katevoss** [comment]
@mbookman thanks for reporting this! There are a few other special characters in a notebook name (like @ + = \ / ) that caused the same error which we are now catching and preventing users from entering.
