### ISSUE TITLE
New clusters should set the Cloud Platform scope for users

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1035]
Leo recently added the ability to set the "Cloud Platform" scope on their clusters. This allows users to dispatch jobs to dSub, cloud ML, and other Google cloud products directly from their notebooks. We should ensure that all new clusters we create going forward include this scope.

Leo issue: https://github.com/DataBiosphere/leonardo/issues/542

**Comment by mbookman** [comment]
I filed a related issue a while back - see #998.
Any update on when this would get into Terra?
We've been using it for more and more analyses and a nice case where calling dsub from a notebook came up.

**Comment by bradtaylor** [comment]
Sorry for missing the connection on these two issues, Matt. I'm closing this as a duplicate and elevating yours

**Comment by bradtaylor** [comment]
Per discussion in #998, I am reopening this. It is insufficient for dsub and also useful for other things. Brett is working on it now.

@mbookman @deflaux is there a quick (non-dsub) command that Brett could run to test that his change to add the scope is having the desired effect?

**Comment by deflaux** [comment]
In a native GCP project with CloudML Engine enabled, command `gcloud --project <YOUR-NATIVE-GCP-PROJECT-ID> ml-engine models list` should return `Listed 0 items.` or something similar.
