### ISSUE TITLE
Authorization domain picker shows group twice

### ISSUE THREAD

**Issue by seanhorgan** [DataBiosphere/saturn-ui#1044]
I created a new group called sean_private. I then created a new workspace and when I selected the Authorization domain dropdown picker to select one, it displayed sean_private twice.

![screenshot 2019-01-09 at 5 10 23 pm](https://user-images.githubusercontent.com/428857/50939446-c2765a00-1431-11e9-97c0-808d9fe0a645.png)
![screenshot 2019-01-09 at 5 10 45 pm](https://user-images.githubusercontent.com/428857/50939450-c6a27780-1431-11e9-92bc-480e3be32c1e.png)

**Comment by katevoss** [comment]
@seanhorgan Thanks for reporting this, I was able to recreate the issue when a user is both an Admin and a Member of the same group. This causes the group to show up twice in the Auth domain picker, when it should only show up once.
