### ISSUE TITLE
Move the rerun failures affordance out of the dropdown

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1047]
We've had multiple feedback reports that folks can't find the 'rerun failures' affordance in it's current position in a dropdown. We've got space in the main table (which only has 4 columns We should put it in the rows, to the right of 'status', when there are failures. We can shrunk the 'Job' column if needed, as this is currently huge.

**Comment by katevoss** [comment]
Related to #1127
