### ISSUE TITLE
When user has 0 workspaces, add information about how to start using Terra

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#1048]
When a user first logs in or when they have 0 workspaces, the Workspace page looks very empty:
![Screen Shot 2019-01-10 at 11.07.09 AM.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/691b854f-9c27-4592-8579-aac4ff4096b1)

We should add some information about how they can get started using Terra, including links to documentation or how to create a workspace (and what a workspace is).

**Comment by bradtaylor** [comment]
This is planned as part of a larger epic building in documentation to our day1 experience flow. Going to close this for now. Will exhume when we're prepared to approach this flow
