### ISSUE TITLE
Change conditions of NPS survey display to be more permissive.

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1062]
Currently, the NPS survey is only triggering based on an engaged usage activity (workflow launch, notebook close). This was a good first step. But it's become clear we're missing feedback from active users whose journeys do not involve these activities (PIs who manage billing and groups, etc).

We want to decouple NPS from active usage and initially display the widget whenever the user logs into the site. We don't want to ask for an opinion while the user is still judging feature fit, so we're instituting a time delay. The new condition for initially displaying NPS widget:
_Whenever the user logs in, if it has been >24 hrs since the user first registered._

In addition, we want to increase the frequency with which we re-prompt from once per month to once every _2 weeks_

**Comment by elizzhao** [comment]
24hr timer starts by pushing a first log-in time value into Thurloe
