### ISSUE TITLE
FR: allow users with edit privileges to open notebooks read-only

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/saturn-ui#1070]
Very often I want to open a notebook just to read it, but when I have edit privileges on the notebook, it opens read/write and that can lead to inadvertent changes. Sometimes this occurs with my own notebook, but even worse is that it sometimes happens with shared notebooks.

It would be great if there were an option to open a notebook read-only. In the Workspace/Notebooks tab, I'd like to see the "..." component on the notebook tile have options for "Open" and "Open read-only".

Note that there is currently no option "Open", which I think is usability issue. The default action of clicking on the notebook tile should also be an explicit option in the context-sensitive menu.

**Comment by seanhorgan** [comment]
Somewhat related to #1085

**Comment by bradtaylor** [comment]
@katevoss Please be aware of this request as you're adding read-only previews during cluster starts per #1085. Does it make sense to do these issues at the same time?

**Comment by katevoss** [comment]
I think I can add an option to the menu to open a notebook as "Read-Only" when a user has edit access as a part of #1085, yes.

**Comment by mbookman** [comment]
This is such a fantastic feature. Thanks @katevoss !

The implementation is so thoughtfully done.
The very clear bar across the top with "Viewing read -only" message and then the "Open in..." options - this has really elevated day-to-day workings with notebooks in Terra!
