### ISSUE TITLE
Make the whitelist easier to use

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1078]
For users who are not already registered, and are not part of the @broadinstitute, @verily.com, or @channing.harvard.edu emails, we need to check them against a whitelist in a more easily managed fashion. This is for users we want to directly reach out to in order to invite them to try terra for the first time.

Acceptance Criteria
* Any Saturn developer, product manager, or customer success project manager can add to this at any time
* It should not require UI deploy, and should take immediate effect
* Users should be added in a free-text list that we don't have to md5 hash. 
* It should not be publicly findable via this repo. 
* Ideally, it should also be useful for defining cohorts in the metrics data warehouse

**Comment by breilly2** [comment]
1. Check email domain
2. Check registration status
3. Check whitelist - both existing MD5 and new service

**Comment by katevoss** [comment]
Adding Comms as another group that needs to be able to add to the whitelist.
