### ISSUE TITLE
Make Access Free Credits banner dismissable

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#1093]
Once a user has clicked "Start Trial" when they are enabled in the Free Credits Trial, they see a banner that says "Access Free Credits". Currently this banner will stay at the top of their screen until they are disabled or terminated from the Free Credits. 

We need to give them a way to "snooze" or "dismiss" the banner so that they can "snooze it" for a period of time (x weeks) or dismiss it permanently. 

@bradtaylor to add additional detail

**Comment by katevoss** [comment]
Once a user has free credits, we could add an item to the left sidebar menu that says "Free Credit Trial" which links to the Free Credit program information. When a user dismisses the banner, we could open the sidebar to show them that they can still access the Free Credit information and sign up there.

In the future when we have better cost reporting, it could be helpful to have a progress bar in the left sidebar that displays how much of the free credits that a user has used, like "$250 of $300 available".

**Comment by dglazer** [comment]
fyii, here's a manual workaround from @dmohs : with the banner showing, enter the following text in the console: `document.getElementById('root').children[1].remove()`

**Comment by bradtaylor** [comment]
@dglazer This was meant to be a temporary fix so that users can remove the bar. It should have been rolled out yesterday. A full dismiss with a less obtrusive sign-up option will follow asap. We've had to rush a bit to meet the needs of NHS workshop. I'm sorry this impacted your ability to demo the platform. I take responsibility for that.

**Comment by dglazer** [comment]
Thanks for the fix -- right now I can dismiss the banner, and it stays
missing for that session, but it comes back when I open a new tab. Is that
Working as Intended? (Okay if so; I'll submit a much lower-priority feature
request to give me a way to make it go away for good.)

**Comment by elizzhao** [comment]
Yes, that's working as intended. We do have a ticket on creating a "dismiss forever" for the banner that will make it go away for good: https://github.com/DataBiosphere/saturn-ui/issues/1103
