### ISSUE TITLE
GDPR Cookies Consent

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1096]
GDPR requires websites that target EU residents to solicit consent to use cookies. We should be compliant with this requirement.

If we are using cookies in the process of setting up websocket proxying to Leonardo, then this is an essential cookie that we should acknowledge but not require consent for.

If we are using cookies for counting users and observing feature utilization via New Relic, we should provide users with a control to deny collection of those cookies via a popup interaction that users must accept before continuing to use the site. 

Work with David Bernick on language

You will see similar popups on other websites. Here is an example:
![Screen Shot 2019-01-18 at 1.59.32 PM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/2704c2d2-0df9-42ba-8432-7741fb834b81)

**Comment by bradtaylor** [comment]
@davidbernick Some questions from refinement:

We have 2 essential cookies (google login, leo re-authentication). We have 1 non-essential cookie that we can find: New relic. This should be GDPR compatible because it only includes a session id, not user info.

Do we just need to say something like "by continuing to use this website you agree to our use of cookies" or do we need to provide some sort of management to turn off specific non-essential cookies?

If it's just a notice, not management, can we put it in terms of service? Or do we need the popup?

**Comment by breilly2** [comment]
Google Platform JS (authorization)
Google Analytics?
Newrelic - https://docs.newrelic.com/docs/browser/new-relic-browser/page-load-timing-resources/new-relic-cookies-used-browser#gdpr
    Double-check settings


Is it sufficient to include a statement in the TOS?

**Comment by davidbernick** [comment]
We need the Cookie Consent if we're going to use Google Analytics. 

NR is probably ok.

**Comment by bradtaylor** [comment]
UX under discussion was a warning above the login buttons, and an update to the TOS to cover cases where returning users are already logged in. We need language for a small statement above the signing buttons

**Comment by breilly2** [comment]
We are not using Google Analytics.
We are not tracking user identifiable information with Newrelic so that's not a concern.

We are tracking users through their Google sign-in cookie and with 2 leo cookies.

Add statement to TOS to cover leo token and people who are already signed in.
Add notice above sign-in button (2 places - sign-in wall and hamburger menu)
* "By using our websites and services you are agreeing to the use of Cookies."

**Comment by bradtaylor** [comment]
Some more information regarding what we do with cookies:
"Terra uses cookies to enable sign on, and to provide anonymized statistics to our development team regarding how the site is used. For more information, see our privacy policy" 

That should be in the TOS statement. For the login button, there should be a 'learn more' that triggers a popup with that language and an 'ok' button

**Comment by elizzhao** [comment]
Added cookie policy above sign in and updated TOS with language on our cookie usage.
