### ISSUE TITLE
Full dismiss of free-credits banner

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1103]
Currently we have a big green bar at the top of the Terra page that calls out for a user to sign up for free credits. Once a user has signed up, it calls out to learn how to use the free credits.

This big green bar is a good call to action, but is extremely obtrusive. We presently allow users to dismiss the bar temporarily- it re-appears whenever the user opens or refreshes the page. The dismiss button should be made a 'dismiss forever'.

In parallel, at the bottom of the left-hand nav, there should be a more permanent affordance for free credits. It should say either 'Sign up for $300 in free cloud credits' with a button, or 'Access your free cloud credits' with a learn-more link. If user's free trial has expired, show "Your free trial has ended" with a dismiss forever that remove the item from the nav bar

**Comment by elizzhao** [comment]
PR #1140 fixes this. Future improvements to free credits UI are being tracked by #1132
