### ISSUE TITLE
Migrate NPS response data into KPI database in BigQuery

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1121]
Migrate our NPS response data from cloud datastore to the main Key Performance Indicator metrics database in BigQuery. This is needed for two things:

1. Driving a dashboard of our key success metrics:
* Total NPS interactions (overall, by month)
* NPS response rate (overall, by month)
* Avg response score (overall, by month)
* Number of promoters (those who answered 9 or 10), neutrals (7 or 8), detractors (0-6)
* NPS (overall, by month)

2. Creating cohorts of 'Promoters', 'Neutrals', 'Detractors' and looking for different usage/experience patterns among these cohorts.

This process can be manual or automatic, but we should be able to migrate these data at least once per week, without an excessive drain on developer productivity

**Comment by katevoss** [comment]
Reviewing and finishing a PR (https://github.com/broadinstitute/workbench-analytics/pull/6) that will add Rex to the nightly Jenkins job that will pull from Datastore and import to BQ.

**Comment by katevoss** [comment]
Data has been migrated to prod! Pending final review of Jenkins PR but this is just about complete and unblocks #1122 and #1123.
