### ISSUE TITLE
Create a dashboard of our key NPS metrics

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1122]
Create a dashboard displaying the following metrics related to NPS:
* Total NPS interactions (overall, by month) - Target = 100% of active users
* NPS response rate (overall, by month) - Target = 25% of active users
* Avg response score (overall, by month)
* Number of promoters (those who answered 9 or 10), neutrals (7 or 8), detractors (0-6)
* NPS (overall, by month) - Target = 10

Acceptance Criteria
* There exists a dashboard where success metrics can be viewed at any time
* Dashboard is editable by the product team, and readable by workbench leadership (especially Ilyana Rosenberg the reporting owner, and Anthony)
* This dashboard can be powered out of Rex Datastore. However, it is preferably exposed through Looker, derived from BigQuery, alongside other BVDP contract milestones

**Comment by bradtaylor** [comment]
@breilly2 Can we please align on an expected completion date so that I can message this to the XFN group?

**Comment by breilly2** [comment]
@bradtaylor I'm aiming to have something ready for review by the end of the week. I expect at that time it will still need some tweaks before being considered complete.

**Comment by breilly2** [comment]
https://looker.dsde-prod.broadinstitute.org:8080/dashboards/8

**Comment by breilly2** [comment]
https://looker.dsde-prod.broadinstitute.org:8080/dashboards/8

**Comment by breilly2** [comment]
_Before_ making use of the data from this dashboard, we _must_ address the maintenance of the `wb_developers` table. The percentage of responses from people who should definitely be on the exclude list is too high for the numbers to be meaningful.
