### ISSUE TITLE
Alter the NPS collection widget to drive response rate

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1124]
We critically need an NPS baseline. This is among our most important organizational objectives. It is worth some compromise in user experience best practices to achieve this. It is even worth artificially deflating that baseline by mildly annoying our users if it allows us to collect it!

Given that our active user numbers are low during Beta phase, acquiring enough data to supply a reliable baseline means maximizing our response rate.

We wish to make the following alterations to the NPS collection widget to achieve this

Currently, we ask a generic question like "how are we doing", with an option to dismiss the widget. If a user opens the widget they see 2 qualitative questions.

The numerical NPS question should be surfaced by default. Further, we should remove the option to close the widget without responding to the numeric question.

If the user answers the numeric question, the widget should expand to present the two qualitative questions. At the same time, the user should gain the ability to dismiss the widget without answering the qualitative questions

**Comment by katevoss** [comment]
Based on our discussion today, the alternations will now be:
- the rating score will be shown by default when we show the NPS widget
- when a user clicks a number, we will show additional optional questions
- if a user clicks the x to close the modal at any time, nothing is submitted (matches current behavior)
