### ISSUE TITLE
Link to unfiltered view of job manager from lefthand nav

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1126]
Add a 'Your jobs' section beneath the 'Your Workspaces' section of the lefthand nav. This should link the user to https://jobs.terra.bio.

Link should open job manager in new tab

**Comment by breilly2** [comment]
Put a feature flag around this to allow for quick rollback.

**Comment by elizzhao** [comment]
closed by #1151, link update being tracked by #1155
