### ISSUE TITLE
Point 'view job details' link to filtered view of the job manager

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1127]
In the workspace submission history, each submission entry includes a 'view job details' link, that currently brings the user back to the FireCloud monitor tab.

Instead, we should link to Terra Job Manager, filtered by the workspace ID and submission ID. Rawls is putting these on every workflow as job labels. These labels can be specified as query parameters in a Job Manager URL

Get an example of one such parameterized URL from Job Manager team. This is the URL that should be linked from the 'view job details' affordance

links should open job manager in new tab

**Comment by katevoss** [comment]
It will likely be relatively easy to complete #1047 at the same time as this issue.

**Comment by breilly2** [comment]
Probably convenient to do #1046 at the same time.

**Comment by breilly2** [comment]
Put a feature flag around this to allow for quick rollback.

**Comment by elizzhao** [comment]
closed by #1151, link update being tracked by #1155
