### ISSUE TITLE
"Admin, Member" in group page is confusing

### ISSUE THREAD

**Issue by melissachang** [DataBiosphere/saturn-ui#1166]
I added Willy to the group and checked both "Admin" and "Member" boxes in the Add User dialog. Now he has "Admin, Member" in the group page:

![group](https://user-images.githubusercontent.com/10929390/52449209-47b16500-2aeb-11e9-9e42-5f5e60790e2b.png)

Is "Admin, Member" the same as "Admin"? If not, how are they different? If so, can we just show "Admin" for both?

**Comment by bradtaylor** [comment]
@zarsky-broad I believe you are addressing this now. I'm assigning to you and marking in progress. Once your changes roll out can you close this as fixed?

**Comment by zarsky-broad** [comment]
Just got merged! #1255
