### ISSUE TITLE
Add FR process to the README

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#1174]
Users are starting to add Feature Requests directly to the Saturn Github repo. We want them to submit FR's through the Comms team first for triaging and consolidation.

Add information from the Comms team to the Readme to clarify this for users.

**Comment by tmm211** [comment]
Feature Request section: https://broadinstitute.zendesk.com/hc/en-us/community/topics/360000500452-Feature-Requests

Article about the process: https://broadinstitute.zendesk.com/hc/en-us/community/posts/360040112171-Welcome-to-the-Feature-Request-section-
