### ISSUE TITLE
Clicking on Workspaces exits to Home Screen - does not refresh to Workspaces Page

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/saturn-ui#1228]
When I am in the Workspaces page and click on the word Workspaces in the top left hand corner, the Workspaces page does not refresh. Instead, it goes back to the Terra Home page.
![screen shot 2019-02-27 at 9 58 16 am](https://user-images.githubusercontent.com/43828038/53499796-19360280-3a77-11e9-9c08-c25b5731b7c6.png)
![screen shot 2019-02-27 at 9 58 29 am](https://user-images.githubusercontent.com/43828038/53499801-1cc98980-3a77-11e9-8c98-4d98b1c7acb1.png)

**Comment by bradtaylor** [comment]
Lou and Jerome are reviewing the way that navigation breadcrumbs work generally. Ideas include a more consistent breadcrumb and an explicit home button in the lefthand nav. These designs are evolving. I expect them to address this inconsistency. I'm going to close this as "wont-fix" for now, with the expectation that we'll be revisiting this in Q2 as part of a larger effort.
