### ISSUE TITLE
Adding Feature Request Link to Contact Us widget in Terra app

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/saturn-ui#1240]
It would be really nice to have the Feature Request page linked if a user chooses "Feature Request" from the options when sending in a question from the Contact Us widget in the app. Right now, the request comes to Zendesk at which point they get a reply redirecting them to post on the Feature Request forum in Community.

FR post page: https://broadinstitute.zendesk.com/hc/en-us/community/topics/360000500452-Feature-Requests
<img width="473" alt="screen shot 2019-02-28 at 3 35 50 pm" src="https://user-images.githubusercontent.com/43828038/53597164-7614e400-3b6f-11e9-836f-4d85174b172f.png">

**Comment by bradtaylor** [comment]
Speaking with @schaluva in person we're going to handle this a slightly different way
