### ISSUE TITLE
Notebooks card updates

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1246]
Some feedback on the notebooks cards- they are unusable compared to list view because the names get clipped off. We should:
* Remove the jupyter logo
* Wrap the notebook-name title text

Matt and Nicole have asked us to move to list view by default. That's a separate matter. Here, we're improving the cards view.

**Comment by bradtaylor** [comment]
Can take this opportunity to move to the new notebooks card design (minus the icon):
https://projects.invisionapp.com/d/main#/console/16562871/343437622/preview

**Comment by elizzhao** [comment]
Card view was updated to match the old mocks and solve the aforementioned problems. 

Removal of the card view entirely is coming in the future: see #1272.
