### ISSUE TITLE
Add 1000 genomes to the data repo.

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1247]
Add 1000 Genomes to the Data Library.

Image: https://i.pinimg.com/originals/8a/3c/d1/8a3cd14c02a13644a36491f7caaa0862.png
Description: "The [1000 Genomes Project](http://www.internationalgenome.org/about) ran between 2008 and 2015, creating the largest public catalogue of human variation and genotype data. The goal of the 1000 Genomes Project was to find most genetic variants with frequencies of at least 1% in the populations studied."
Participants: 3,500
"Browse Data" link: https://test-data-explorer.appspot.com/

Ordering: List should be in alphabetical order.

**Comment by katevoss** [comment]
This will be alphabetized and will be listed first on the data page.
