### ISSUE TITLE
Error for non-whitelisted user

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1254]
When a user is not on the whitelist, we should be taking them to a static page with the text:
"Terra is under development. If you are interested in contributing feedback as part of our user panel, please email saturn-dev@broadinstitute.org."

However, we are currently instead showing a generic error message:
![Terra.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/5fc4b238-6fd0-4f40-b5db-295ea6f44bcc)

This may be related to the recent changes to make the whitelist more permissive. Return the UX to the previous state (static page with text).

In addition, update the text on that page to the following:
"Terra is currently in a closed-access beta phase. If you are interested in contributing early-access feedback as part of our user panel, please email us at info@terra.bio"

**Comment by zarsky-broad** [comment]
I think the issue is around the permissions on that bucket. I don't have access, @panentheos do you?

**Comment by kleighwe** [comment]
Note team and @bradtaylor: Updated permissions should have resolved the permissions issue. We should confirm and then update the wording per the description.
