### ISSUE TITLE
Privacy policy change.

### ISSUE THREAD

**Issue by davidbernick** [DataBiosphere/saturn-ui#1267]
1. Please update the Firecloud privacy policy with this text: https://docs.google.com/document/d/1dLjVvii1GX6T-7Ko7kJJtNK_X1cFMUdqEJaWAN9SSZ8

2. Please add this to ToS (and make sure it activates the "users have to re-accept"):
"Privacy: Privacy policy, including privacy policy of uploaded data, is here <link to privacy policy>. You agree to read and consider before uploading data. "

"HIPAA, Protected Health Information, and the Clinical Compliance Features:

Firecloud/Terra is not a Covered Entity as that term is defined in the Health Insurance Portability and Accountability Act of 1996, as amended, and its related regulations (collectively, "HIPAA"). On occasion, Firecloud/Terra may agree in writing with a user to perform services for the user in the storing PHI. We recommend that such users enter into a formal agreement with Terra/Firecloud.

Firecloud/Terra does offer clinical compliance features as part of its service ("Compliance Features") for users who wish to upload, store, or otherwise transfer PHI, as well as users who are using the Site in connection with their clinical operations. Users who desire to upload, store, or otherwise transfer PHI using the Site must implement all of the required Clinical Features and must enter a formal agreement with Firecloud stating that. The uploading, storing, or transferring of PHI using the Site by users that have not implemented the Clinical Features is strictly prohibited. You agree that, unless you have implemented the Clinical Features, you will not upload, store, or otherwise transfer PHI using the Site. 

You acknowledge that this may require you, in some instances, to anonymize sequence data prior to uploading it to the Site. You further agree to indemnify and hold harmless Firecloud/Terra of and from any and all claims, demands, losses, causes of action, damage, lawsuits, judgments, including attorneys' fees and costs, arising out of or relating to your uploading, storing, or transferring of PHI without having fully implemented the Clinical Features."

**Comment by bradtaylor** [comment]
Speaking with Bernick in person, we're going to say "Terra" in place of "FireCloud/Terra" throughout the privacy policy

**Comment by zarsky-broad** [comment]
Users will have to accept the new policy when they log in.
