### ISSUE TITLE
Registration email should say "Welcome to Terra", not FireCloud

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/saturn-ui#1271]
I just registered an account through Terra and received an email:

> Subject: FireCloud Account Activation
> 
> Welcome to FireCloud!
> <etc>
 
Presumably all of this will be changing by May 1, but it will be a very nice milestone and element of our new user experience to be greeted from Terra and the Terra team.

**Comment by katevoss** [comment]
I think this is a dupe of #801 fyi

**Comment by mbookman** [comment]
Thanks @katevoss. Definitely in a similar vein.

**Comment by katevoss** [comment]
I'm going to close this issue in favor of tracking work on the original issue. The changes will happen at the same time.

**Comment by bradtaylor** [comment]
@katevoss if you are closing an issue as a duplicate, please apply the duplciate label
