### ISSUE TITLE
Initial find-a-tool from workspaces

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1282]
There's currently no way in a workspace to find a tool. We are addressing this more holistically in Q2. However, let's do a quick improvement today. The most achievable option is to place an emphasis on the feature workflows, with a terra->firecloud->terra loop for user created content. Very similar to what is done today in library, but accessible from the workspace. An example UX deck is here and has been thumbed up from design:
https://docs.google.com/presentation/d/1V0AF_s8HPEEFlB2WqIJfGkap_Vh9r0MnJW4uvRfhgIk/edit#slide=id.g51d3687212_0_5

**Comment by zarsky-broad** [comment]
When viewing the tools tab in a workspace, a user now will have a button to browse and import a featured method, or go directly to the FC or Dockstore repo.
