### ISSUE TITLE
Consider centralizing error messages and labels

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#154]
Jeremy brought up that it would be nice if a designer can easily make a change to a label or error message if, during user testing, it is found to be unclear. If and when we allow this, I want the process to include a review by a developer to ensure the messages don't lose accuracy in the change.

Propose a process that the team (design and engineering) agrees on. Document as needed.

**Comment by bradtaylor** [comment]
Team prefers to commit to rapid resolution of text changes, which can go straight to dev without requiring review (over implementing/maintaining a code solution).

We will re-evaluate this decision in 2 months once text changes have been requested/resolved

Jeremy agreed to this during refinement
