### ISSUE TITLE
UI attempts to create clusters that already exist

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#166]
![Screen Shot 2018-05-21 at 11.07.01 AM.png](https://images.zenhubusercontent.com/5a95bd6a4b5806bc2bc8a523/eaa12f54-a986-4f4f-9dab-6a0671f0906b)

Version: 3bf2f4d169e92aaaab9afbf8d3b2658a51bb4de0

**Comment by dmohs** [comment]
I am still seeing these errors in my console after #151.

**Comment by panentheos** [comment]
This is fixed by #178
