### ISSUE TITLE
Infinite spinner on notebooks

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#167]
![Screen Shot 2018-05-21 at 11.12.07 AM.png](https://images.zenhubusercontent.com/5a95bd6a4b5806bc2bc8a523/cc6eb92a-a4ae-42bb-9289-890a0884b4f8)

Version: 3bf2f4d169e92aaaab9afbf8d3b2658a51bb4de0

**Comment by bradtaylor** [comment]
Spinner happens where there is no cluster.
Probably fixed by #151 , such that there will always be a cluster you own

**Comment by dmohs** [comment]
This spins for the duration of cluster creation, so the entire time I am visiting the page. I don't think that is an acceptable user experience. Re-opening.

**Comment by zarsky-broad** [comment]
Hmm. What if, when there isn't an active cluster, we reload the cluster list every 30 seconds? In addition to adding some 'waiting for cluster to be ready' text.

**Comment by dmohs** [comment]
What would the behavior be if all of my clusters were stopped?

**Comment by panentheos** [comment]
Fixed by #208
