### ISSUE TITLE
Windmill Integration Flow

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#171]
We need to accept data from the U. Chicago Windmill data explorer for NIH Commons. Unlike Boardwalk, who just hauled off and implemented a complete data send, Chicago is going to delegate sign-in and workspace selection to the Saturn UI.

To this end, they will link users to our UI. In doing so, they will send us a signed URL at which data can be retrieved from their system. In the Saturn UI, users should sign in and select a workspace (very similar to the Dockstore flow).

We will then pass the signed URL to a new backend API endpoint that the Content and Discovery team is creating, which will ingest the data. On successful ingest, the user should be taken to the data tab of the workspace they have selected.

Ask Hussein for the API specification.

**Comment by bradtaylor** [comment]
Given that we are reusing the workspace selection design from the Dockstore import flow, we are going to proceed without formal visual design (@zarsky-broad can make any calls regarding details)

**Comment by helgridly** [comment]
Swagger definition for our side (not implemented yet, wanted to get it spec'd for you ASAP): https://github.com/broadinstitute/firecloud-orchestration/blob/3591_bagit/src/main/resources/swagger/api-docs.yaml#L2467

Ping me if you have Qs.

**Comment by dmohs** [comment]
Note that we currently use "import" for Dockstore. It might be better to rename this to "import-workflow" so it can be distinguished from "import-data" for this case.
