### ISSUE TITLE
Rename "workspace" to "project"

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#172]
This is a product requirement. Since the similarity is dangerously close to google project and billing project, we need to be careful about calling these out when necessary. In the code, it may even be useful to call these "user projects" or "researcher projects" to distinguish them.

**Comment by bradtaylor** [comment]
How these are referred to in code belongs to the engineers. If I had to offer a suggestion, it would be that the objects currently referred to as 'workspaces' be referred to simply as 'projects'. Other potential collisions should get additional qualifiers ("google_project" or "billing_project"). That's going to be my usage in product documentation and in the app itself.

**Comment by bradtaylor** [comment]
We are not doing this!
