### ISSUE TITLE
Blank screen when Sam is down

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#184]
![Screen Shot 2018-05-23 at 3.07.52 PM.png](https://images.zenhubusercontent.com/5a95bd6a4b5806bc2bc8a523/889b2304-4a1f-483f-a62b-e0e92f95b53e)

**Comment by bradtaylor** [comment]
If any service can't be reached (Rawls, Sam, Leo) should we show a helpful error message? I imagine an error banner or popup with a link to pingdom.

**Comment by panentheos** [comment]
This will be largely solved by #127

**Comment by panentheos** [comment]
Fixed by #127 (you will now get an error message)
