### ISSUE TITLE
Retrieve a data manifest containing UCSC Blue Box UUIDs pushed from the Boardwalk data explorer and display it as a static table in a Project

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#2]
1. User logins into Boardwalk (UCSC) with google ID
2. User applies filters and selects a subset of the data -> creates a manifest which includes references to UCSC’S Blue-Box UUIDs  
3. User clicks ‘send manifest to Saturn’
4. Saturn as an application retrieves the manifest from Boardwalk and populates the Project data display
5. User is directed to the Saturn Project data-display screen, and views a static table of information from the manifest

For the purposes of this issue we can assume there is only one pre-populated Project in the application, and that all data pushes should be sent to this single Project. Choosing projects from a list and project-creation will follow as subsequent stories

The handover process represented by step4 above is discussed [here](https://docs.google.com/document/d/1b4qKQ9apQVop-ejvSKs3ke73rLpk_J0xhR8OPD_eJvU/edit?usp=sharing)

The data manifest is being represented in bdBag format (essentially, a TSV packed inside an XML wrapper). It's unclear at this point if the data retrieval API being exposed by Boardwalk will return the full bdBag, or just the TSV (we can make requests to them regarding our preferred functionality!)

The data retrieval API has not been provided by UCSC yet- a significant source of risk.

We have not yet received an example bdBag/TSV. We should request this of UCSC ASAP.

**Comment by bradtaylor** [comment]
See UI design mocks with a clickthrough path [here](https://invis.io/4XG2G91BPST)
"Data Explorer" is a stand-in for Boardwalk in these mocks

**Comment by kcibul** [comment]
We have also made significant progress towards unified auth between boardwalk and our system so we can also make more direct interactions (ie assume they can make authenticated calls to all our APIs )
