### ISSUE TITLE
auth UI should give feedback on exceptions

### ISSUE THREAD

**Issue by brandonmp** [DataBiosphere/saturn-ui#210]
Very minor but wanted to make a note 

When registering new account, errors from server are apparently swallowed & loading state just hangs in UI.

e.g. registering w/o last name leads to hanging `loading...`, but console kicks out:

```
Uncaught (in promise) {
  "statusCode": 400,
  "source": "FireCloud",
  "causes": [],
  "stackTrace": [],
  "message": "requirement failed: last name must be non-empty"
}
```

**Comment by panentheos** [comment]
#127 will make this error visible, but still not friendly. We should do some work to surface this particular error in a nicer way.

**Comment by brandonmp** [comment]
in this very specific instance (required fields empty), client side validations would help too--even something as trivial as denoting required fields w/ `*`

**Comment by panentheos** [comment]
That is in fact what we ended up doing!
