### ISSUE TITLE
Notebook links should be sharable

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#212]
Currently, opening a notebook gives me a notebooks.firecloud URL that contains my cluster:
https://notebooks.firecloud.org/notebooks/fc-product-demo/aa-try-saturn/notebooks/NHS1_Smoking_and_Lung_Cancer/Smoking%20and%20Lung%20Cancer.ipynb

If I email you this link, you get a very ugly message:
{"statusCode":401,"source":"leonardo","causes":[],"exceptionClass":"org.broadinstitute.dsde.workbench.leonardo.service.AuthorizationError","stackTrace":[],"message":"'bradt@broadinstitute.org' is unauthorized"}

Why?

Because you do not have my cluster
Because your cluster might be paused
Because the notebook in question is not localized to your cluster.

I should be able to provide a direct link to their notebook. You should only be able to open this link if you have 'can-notebook' permission in the notebook's workspace. Otherwise, we should show you a nice error message telling you to request that the workspace owner share give you WRITE access to the workspace.

**Comment by kleighwe** [comment]
@dmohs is this a Leo thing?

**Comment by dmohs** [comment]
@kleighwe I think this likely needs to be solved in the Saturn UI. Also, update your GitHub profile to include your name ;)

**Comment by bradtaylor** [comment]
apparently ipython does not work in an iframe. Some sort of cross-origin header issue

**Comment by bradtaylor** [comment]
Blocked by leo change
