### ISSUE TITLE
'Download' of data tables

### ISSUE THREAD

**Issue by kcibul** [DataBiosphere/saturn-ui#218]
I mentioned this on the slack room, but in FireCloud the ability to 'download' a TSV of the data in the samples, participants, etc tab is critical to getting analysis work done.  Recently running through a WGS set of samples, there were innumerable times when I would grab that TSV and pump it through Excel or unix tools (cut, sort, uniq, awk, grep) to grab out a list of data.

In Firehose, our table widget actually had "Download to" CSV, TSV, Excel and Clipboard.  Of those, I'd say CSV was rarely used, XLS was handy but easy enough to get there from another format.  TSV and Clipboard were amazingly useful.  Would be great to have this feature in Saturn.

Discussion Points:
- teach Rawls how to download tsv

Requirement:
- "Copy" --> could copy current page.
- TSV Download --> all records
- Must work with non-FC data model data

**Comment by zarsky-broad** [comment]
[This](https://www.npmjs.com/package/streamsaver) could turn out to be useful here. Note that the compatibility data is out of data

**Comment by kcibul** [comment]
does this mean it's implemented?  

@kleighwe  process wise, it might be good to either link to PRs, or close with a resolution comment as it's a public repo and while I can go email people users in the future will be looking here

**Comment by MattPutnam** [comment]
It's in dev, and yeah I forgot to link it to the PR. It won't let me connect it now that the issue is closed.

**Comment by kcibul** [comment]
haha that's the best answer I could have gotten, thanks Matt!
-------------------------------
Kristian Cibulskis
Director, Platform Engineering and Architecture, DSP
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org
