### ISSUE TITLE
Error when switching page size in data table

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#226]
1) Set page size to 10.
2) Go to a late page.
3) Set page size to 25.

![Screen Shot 2018-06-05 at 5.15.45 PM.png](https://images.zenhubusercontent.com/5a95bd6a4b5806bc2bc8a523/2f7f44c4-1493-4014-b5a8-22cc802be573)

**Comment by MattPutnam** [comment]
Page size change needs to also set page number to 1.
