### ISSUE TITLE
Warn users when attempting to leave an unsaved form

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#230]
Help user's to avoid losing work by warning them when they leave a form that has data entered into it.

## Engineering Design
There are two separate events to catch. The easier of the two is a window or tab close. That involves adding a `window.onunload` (or similar) handler to show a modal.

The other event is navigation (`hashchange`). Since our routing involves listening and responding to this event, we can control the behavior. However, we only receive this event after the window hash has changed, so we'll want to be careful about how this is handled so it isn't confusing. It will require experimentation. For example, we may want to try saving the intended destination and using `history.go(-1)` before displaying a modal so the hash appears unchanged while we prompt for confirmation.

**Comment by bradtaylor** [comment]
Will not fix for now. We will autosave form inputs, making this less critical

**Comment by kleighwe** [comment]
@dmohs will add details here on page close event vs navigation event

**Comment by dmohs** [comment]
Given our current implementation, I don't think we need this. If the user closes their tab, restoring it (from Google Chrome's menu, for example) restores the work (because we maintain it in session history). Navigating away and then back again also restores the work. It's true that if a user closes the window, they might experience a bit of panic that their work is gone, but there are enough ways to restore it that they should be able to do so in most cases.
