### ISSUE TITLE
StateHistory leaks unauthorized info

### ISSUE THREAD

**Issue by MattPutnam** [DataBiosphere/saturn-ui#232]
1. Log in as User A and go to a workspace tab that uses StateHistory. Example: Log in as b.adm.firec and go to son-of-jimmy/notebooks.
2. Log out from this page, and log in as User B who doesn't have access to this workspace
3. Observe that although we get the error message, we still see the notebook cards.

Proposal: logging in clears all history

**Comment by dmohs** [comment]
Good catch! I suggest doing this at sign-out. As far as I can tell from a cursory examination of MDN docs, there doesn't exist a "clear" method. The following might be a workable solution:
```javascript
history.go(-history.length)
history.pushState({}, '')
```
`pushState` clears all history beyond the "current page."
