### ISSUE TITLE
Project Deletion

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#264]
I should be able to delete projects on which I have either Owner or Project Owner permission. The delete should be triggered from the following menu already in our UI. NOTE - the delete option should only appear if one has appropriate permission to delete:
![Screen Shot 2018-06-13 at 3.17.00 PM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/f3aa08cf-a2ef-423d-b2ec-7c8ae388f3b5)

Clicking delete should trigger a confirmation modal warning the user that deleting the workspace is permanent and will delete their bucket and any data therein. See FireCloud's modal below
![Screen Shot 2018-06-13 at 3.25.05 PM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/2178d615-2492-4390-9d93-098bed8074ac)

The following alterations should be made to the above modal:
- "...delete this workspace?" should read "... permanently delete this project?"
- "...the associated bucket data" should read "... the associated Google Cloud Bucket and *all its data*".  Here, "Google Cloud Bucket" text should be a link out to the bucket storage console so users can check what is there.

**Comment by zarsky-broad** [comment]
Rather than hiding the delete option in the menu, it should be grayed out, with a tooltip that says "You do not have permission to delete this project."
