### ISSUE TITLE
gs path download modal and DOS URI resolution

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#269]
Where our tables contain GCS paths of the form gs://...
we should display these as a link.

IDEAL BUT OPTIONAL: Only the tail end of these paths should be shown. So for:
"gs://firecloud-tcga-open-access/tcga/dcc/paad/clin__bio__nationwidechildrens_org__Level_1__biospecimen__clin/nationwidechildrens.org_PAAD.bio.Level_1.424.41.0/TCGA-3A-A9IX.clin.txt"
...I only want to see "TCGA-3A-A9IX.clin.txt"

Clicking on one of these links should bring up a File Details modal. This is akin to the file details modal in FireCloud. Here, I want to see:
- The name (that tail end of the path, from above)
- "Preview:" followed by a file preview. See note below!
- File Size = XX.XX GB
- A link that says "View this file in the Google Cloud Storage Browser" that takes me to the bucket folder (in the above example, ...nationwidechildrens.org_PAAD.bio.Level_1.424.41.0)
- A big button that says "Download for $Y.YY*". There should be some small text at the bottom of the modal saying "* Estimated download fee (non-US destinations may be higher)". This should be small.
- All the gsutil info from the FireCloud modal
- An expansion control called "More Information"

More information consists of:
- The full gs path
- The Created date
- the Updated date
- the md5 hash

NOTE ON FILE PREVIEW
This should only show up IF the file is of a type we can preview (which I think is probably txt, tsv, csv, jpeg, png. But I don't know. Whatever the proper set is). I don't want all the extra verbiage around which lines are being previewed. Ideal but optional: start me at the head of the file not the tail (since I can scroll it anyway)

*OK, now for DOS resolution*

For anything with a dos:// URI, such as:
‎dos://dos-dss.ucsc-cgp-dev.org/60936d97-6358-4ce3-8136-d5776186ee21?version=2018-03-23T123738.145535Z‎

Show the full thing in the table. Make it also be a link. Like FireCloud, clicking this link should call whatever google cloud function (little mini service. Called Martha?) handles resolving dos:// into gs://. It should then open the file details on the gs file as normal

**Comment by kleighwe** [comment]
@zarsky-broad can you throw some labels on this? Is this considered infrastructure work?
