### ISSUE TITLE
Tweak behavior of data tab refreshing

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#270]
On the Data tab, when I click the tab header, the page refreshes its data. If I happen to be on page 3 of samples, for example, I remain on page 3 of samples.

If I click the sample data type, the data refreshes but I am placed back on page 1.

I wonder if this is a history state problem. Should we be storing to history only on component-will-unmount so the behavior better matches our expectations?

**Comment by panentheos** [comment]
What are our users' expectations of this behavior?

**Comment by dmohs** [comment]
Good question, and I don't know. @bradtaylor might weigh in, but I think for our first pass we should just have consistent behavior between the two.
