### ISSUE TITLE
Access token expires while using notebook

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#273]
When we call:
```
gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse(true).access_token
```
after the user's token has expired, Google's Auth2 library automatically refreshes it. Since we don't pass this along to Leo, we can expect that the user's notebook session will end after an hour.

All of Us has solved this problem. We should investigate their solution before considering an implementation.

**Comment by bradtaylor** [comment]
Needs a conversation with the AoU and Interactive teams

**Comment by bradtaylor** [comment]
There may be alternatives to cookie based auth. It may be up to us to teach the Leo team how, if we can figure out an alternative

**Comment by bradtaylor** [comment]
@zarsky-broad is going to explore options with Leo team

**Comment by zarsky-broad** [comment]
Seems like it should be fixed by https://github.com/DataBiosphere/leonardo/pull/453. We should test once that merges.

**Comment by zarsky-broad** [comment]
Apparently there's a fix for this in Leo that's been there for a while. We should check with Callisto to see if we can make it work.

**Comment by zarsky-broad** [comment]
Underlying issue tracked by https://app.zenhub.com/workspace/o/databiosphere/leonardo/issues/501
