### ISSUE TITLE
Project clone should deep copy notebook files

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#277]
Currently cloning a project copies all the data in the data model but leaves individual GCS bucket files in place. This makes sense - we don't want people to pay for it twice! But notebook ipynb files in the /notebooks folder should be copied
child of #353

**Comment by bradtaylor** [comment]
Technically, the right answer here appears to do this via the API. We should decide whether it belongs on Content + Discovery (likely) or Cloud Accounts. Brad will take this to the appropriate PMs

**Comment by bradtaylor** [comment]
Notebooks are not the last analysis artifact we will have (python scripts, Rstudio session histories, perhaps others). So how generic do we need to go with our cloning rules?

**Comment by bradtaylor** [comment]
Idea: UIs keep paths they know about and can specify to clone/not-clone them. We need to know where notebooks are to display, localize, save them.

So clone could become "clone with file pattern whitelist"

**Comment by bradtaylor** [comment]
@ahaessly There's an update needed to workspace clone, which is properly on the Rawls endpoint. Do you think this a C+D issue?

**Comment by bradtaylor** [comment]
We're going to drive the copy from the client. We may not be able to handle all the rough edges, but it's the fastest way to get needed functionality in the platform.

Behavior is to implicitly copy all ipynb files in the /notebooks directory.

**Comment by kleighwe** [comment]
Talk to Vikram before starting this ticket!

**Comment by bradtaylor** [comment]
This is being done by Leonardo in time for ASHG. @vkumra-broad Do you have a ticket number?

**Comment by vkumra-broad** [comment]
The priority for this got pushed back, this is not being done for ASHG.
https://github.com/DataBiosphere/leonardo/issues/601

**Comment by bradtaylor** [comment]
@vkumra-broad Thanks for the update! I see that it's in progress. If not for ASHG, do you have an idea when it might land?

**Comment by vkumra-broad** [comment]
I am hoping to get it in for the release after ASHG.

**Comment by kleighwe** [comment]
Blocking ticket in progress.

**Comment by bradtaylor** [comment]
This appears to be in review in Rawls. PR here:
https://github.com/broadinstitute/rawls/pull/1014

**Comment by bradtaylor** [comment]
Backend PR in Rawls was released. According to Matt, the UI requires "one very minor change. When calling rawls to clone a workspace, the UI now needs to tell it which path to copy the notebooks from"

**Comment by mbookman** [comment]
Great news!

For our planning purposes, is the UI update likely to come soon or is there discussion needed around what path(s) to copy?

**Comment by bradtaylor** [comment]
@mbookman UI change PR is linked and in review. We're looking to have it out before Thursday 1/17.
