### ISSUE TITLE
Autosave workflow input/output-binding form inputs

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#278]
Save should be when the user focuses-out of the input field.

**Comment by bradtaylor** [comment]
We need to figure out the right user experience here regarding when we save, how does this affect cancelling changes, etc.

To discuss with design team, Isaac, any interested engineers

**Comment by kleighwe** [comment]
@zarsky-broad to add discussion comments to this ticket

**Comment by zarsky-broad** [comment]
We discussed this; I believe, and I think the conclusion we came to was this as well, that it's best to leave this behavior as-is.

If inputs auto-save whenever the user changes them, then the cancel button is meaningless. Similarly, if a user closes the window, they expect to see the values from the server when they return.

**Comment by bradtaylor** [comment]
Closing as design team has decided current behavior is preferable.
