### ISSUE TITLE
Delete data

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#291]
Remove individual entities from a data entity table. Long requested feature from FireCloud. User must be presented with an appropriate warning that they are about to permanently delete information from their workspace.

Note: This is simply to delete the entry in the data table. Any underlying data files in the bucket are retained (we may handle this separately)

There is a backend API for this.
UX Options: Checkboxes with 'check all box'.  Shift-click to select range (possibly, followup ticket)

~~We do not wish to delete a data entity if it is potentially going to be written to by a running workflow. Given relationships between entities, it is very difficult to know if an entity is in this state. Deleting data should therefore only be an option when no workflows are running for the workspace. Otherwise, the button should be greyed out, with a hover text indicating "Data cannot be deleted from a workspace when workflows are running. See the Job History tab. Please wait for workflows to complete, or abort all running workflows."~~

Only workspace WRITERs should have the ability to delete data. Otherwise the button should be greyed out, with the hover text "You do not have permission to modify data in this workspace" We will add the ability to request such permission as a separate story.

~~UPDATE: Deleting data may 'orphan' data in other tables that carry a foreign key reference. How should we handle this? Adding label "needs product"~~
Rawls handles references between data entities (such as between samples and sample_sets, or participants and samples) in the following manner:
When you hit the delete endpoint, it returns a 409 code along with the full list of entities you'd have to delete (any sets or children that reference the original entities).
So we could reply to the user with a non-editable list of additional entities that would be deleted, and ask them to confirm that's still ok. Then delete the full updated list.
See API here https://rawls.dsde-prod.broadinstitute.org/#!/entities/delete_entities

Based on discussion below we don't wish to prevent data deletion under any circumstance. Instead we should issue a warning listing the running workflows and stating:
"The following submissions currently contain running workflows. Some or all of these may fail if they make use of the data being deleted. Are you sure you wish to delete these data?"

Since we are warning, not preventing, we should handle gracefully the case in which a Cromwell workflow is successful, but Rawls fails to write back it's information to rows in a data table (because these have been deleted!). The appropriate thing to do here is to mark these workflows as failed in Rawls with an appropriate cause (this may be in place already- we should check).

**Comment by mbookman** [comment]
It feels restrictive to me to completely prevent data deletion from a workspace while any workflow is running. As an end-user I think I would want to be able to delete data that I know is not being used within a workflow. A warning would certainly be nice, but I don't feel like I should be prevented (or need to go to the API to work around this).

Is the scenario that is being protected against different than one would expect from other products or systems? I feel like I interact with tools every day where things could go wrong if I delete data that is being processed. That seems like user error and a "global lock" on my workspace feels restrictive.

Is there a common scenario that prompted the tight restrictions around data deletion?

**Comment by dmohs** [comment]
Agree with @mbookman here. I think the right affordance is to give the user the information they need to make an informed choice, but let them make the choice.

**Comment by bradtaylor** [comment]
There is already a design flow for this in invision. The confirmation modal needs some updating to capture some of the exploration from this ticket. See the comment to this effect here:
https://projects.invisionapp.com/d/main#/console/13746874/309146478/comments

But otherwise the flow is fine to proceed with. I am therefore removing the needs design tags
