### ISSUE TITLE
Add TOS acceptance flow to Saturn

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#299]
See the flow being developed in FireCloud here:
https://github.com/DataBiosphere/firecloud-app/issues/42

Note, this issue is blocked on backend work in FireCloud, scheduled to be completed for August.

**Comment by bradtaylor** [comment]
This process is getting worked out first in FireCloud. It has not completed yet. Sync with Ilyana on behavior, designs

**Comment by bradtaylor** [comment]
@panentheos Meeting about this Thursday at 1pm. See @dmohs for location

**Comment by bradtaylor** [comment]
This should also be blocked on the FireCloud UI flow. We have offered to help implement that flow. See David An for that ticket

**Comment by lstrano-broad** [comment]
![Screen Shot 2018-09-18 at 10.51.41 AM.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/ce1553ce-0891-49e2-ad0b-dbbcd30816f4)

**Comment by lstrano-broad** [comment]
New ToS screen uploaded to Invision...
https://invis.io/X7O4787MK52
