### ISSUE TITLE
Move UI config into cloud bucket

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#309]
Our API has a config bucket to hold each environment's config.json. Since the UI, on the other hand, cannot contain secrets, we commit the config.json files into our UI repo.

API keys are not secrets, but various actors within the GitHub community incorrectly treat them as such, causing noise when they are committed into a GitHub repo.

We should eliminate this noise by adopting the API deployment model, injecting the environment's config.json at deployment time.

**Comment by panentheos** [comment]
Is there still anything that requires this treatment? Looking at the config file, I don't believe there is.
