### ISSUE TITLE
Auto delete old versions of app on google cloud

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/saturn-ui#322]
Cloud can only have 210 versions of a service, and it doesn't clean up automatically. This needs to be applied on dev and prod both.

Keep the last X (20? 50? 100?)

See further:
* https://almcc.me/blog/2017/05/04/removing-older-versions-on-google-app-engine/
* https://stackoverflow.com/questions/34499875/how-to-automatically-delete-old-google-app-engine-version-instances
* https://cloud.google.com/sdk/gcloud/reference/app/versions/delete
* https://developers.google.com/apis-explorer/?hl=en_US#p/appengine/v1/appengine.apps.services.versions.list
* https://developers.google.com/apis-explorer/?hl=en_US#p/appengine/v1/appengine.apps.services.versions.delete

**Comment by panentheos** [comment]
Prod will now automatically clean up all but the most recent 10 versions every monday at 16:00 UTC.
