### ISSUE TITLE
Notebooks - actions menu goes off the screen

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#328]
On the notebooks tab, click on a notebook's vertical ellipsis. The dango menu will go off the screen. This happens for both list view (which is the more egregious offender) and for the grid (if there is an element near the edge of the screen).

![Screen Shot 2018-07-02 at 5.44.42 PM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/ccf6d902-1b8f-49e6-9a15-cb3096e90801)

![Screen Shot 2018-07-02 at 5.45.46 PM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/99ccd8ff-6cee-4360-8854-503e12748ae3)

---

Side note:
~1200px is the width at which the signout button goes off screen. 

![Screen Shot 2018-07-02 at 5.50.33 PM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/7c24776e-ce1a-4011-9cd1-daef53ad9d92)

**Comment by zarsky-broad** [comment]
FWIW: 1200px is the width at which we decided the page should wrap rather than start to degrade. We based this on data on the screen widths of Firecloud users.
