### ISSUE TITLE
Notebook ipynb CRUD

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#33]
An analyst can store a notebook they used for Saturn in their Saturn project such that they can access/share it alongside their other project resources.

This includes ability to perform following operations on ipynb files directly in the UI
* Create new
* Duplicate (or clone, whatever)
* Rename
* Delete

See AoU mocks (we want the list toggle, but for some reason the actual 'notebooks' tab screen doesnt show it, just the dashboard)
https://projects.invisionapp.com/d/main#/console/12820961/275889953/preview

See also BVDP rolling UX deck (slide 32) for accessing duplicate/rename/delete options from a card. Note, ignore 'open with' on this slide.
https://docs.google.com/presentation/d/1-JQd63YQZmKLGPSgvSjRXot8OlFmP3r3D2EaEdgYIyE/edit#slide=id.g2f5d876176_0_50

**Comment by bradtaylor** [comment]
@rtitle @calbach @blrubenstein Can you comment on how this is being handled for All of Us?

**Comment by bradtaylor** [comment]
Note, we don't have a good solution on how to do the screenshot style cards. That can be punted to a different issue if we want. We can use a blank card that just has name, created by, last modified.

Note that I just filed https://github.com/DataBiosphere/leonardo/issues/277

**Comment by bradtaylor** [comment]
@zarsky-broad @dmohs Is this going to require eng design on creating the actual ipynb?  A blank ipynb is just a JSON. But in jupyter you typically specify the kernel up front

**Comment by bradtaylor** [comment]
Blank R notebook:
`{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "3.3.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}`

**Comment by bradtaylor** [comment]
Eng design needed: Do we need GCS scope to do this from UI on behalf of the user? If so, is that OK for Google users? If yes and no respectively, what do we do? Run this through FC APIs?

**Comment by dmohs** [comment]
This is some NodeJs code to use a user's pet service account to access a GCS bucket:
```js
app.get('/workspaces/:wsns/:wsname/bucket/list', (req, res) => {
  const [_, token] = req.get('authorization').split(/\s+/);
  rawlsReq(token, `/api/workspaces/${req.params.wsns}/${req.params.wsname}`, (dsRes, obj) => {
    const bucketName = obj.workspace.bucketName
    samReq(token, `/api/google/user/petServiceAccount/${req.params.wsns}/key`, (dsRes, obj) => {
      const jwtClient = new google.auth.JWT(
        obj.client_email,
        null,
        obj.private_key,
        ['https://www.googleapis.com/auth/devstorage.full_control'],
        null
      );
      jwtClient.authorize((err, tokens) => {
        if (err) {
          console.error(err);
          throw err;
        }
        // Make an authorized request to list Drive files.
        storage.objects.list({
            auth: jwtClient,
            bucket: bucketName
          }, (err, dsRes) => {
          if (err) {
            console.error(err);
            throw err;
          }
          // console.log(response)
          res.write(formatObj(dsRes.data))
          res.end()
        });
      });
    })
  })
})
```
Roughly:
1) Grab the bucket from Rawls by getting the workspace details.
2) Grab the user's pet service account from Sam.
3) Use that to create a jwtClient.
4) Use that client to access GCS (I'm just listing the files here).
This gets us the functionality we need without having to ask for GCS scope during sign-in. It can be translated to UI code. We may want to implement this in an API to keep the service account credentials out of the UI, but I don't see this as a requirement for the feature.
