### ISSUE TITLE
Allow new workspace creation upon data import from Data Explorer

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#333]
As a researcher importing data into a workspace from an external data explorer, I would like the option of creating a new workspace in addition to the option of selecting an existing workspace

If passed an AD parameter per #332, any workspace a user creates MUST include the group as an authorization domain, as well as potentially others that the user specifies

**Comment by lstrano-broad** [comment]
![Screen Shot 2018-09-18 at 11.14.36 AM.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/251d17a3-34ae-44d8-9bfc-bc7e8f8cd75e)

Uploaded to Invision...

**Comment by bradtaylor** [comment]
See @lstrano-broad for updated design in invision

**Comment by bradtaylor** [comment]
https://projects.invisionapp.com/d/main#/console/13746874/290428704/preview
