### ISSUE TITLE
Record net promoter score

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#347]
To meet our Y2 goals, we will need to report a net promoter score. The simplified version of this is to gather answers to the question, "How likely are you to recommend Terra to others?"

We should first ask this question of users following the first time they open a notebook or launch a workflow. We should subsequently re-ask once a month

Responses are recorded on an eleven-point scale of [0,10] 
We ultimately want to report the following summaries of this number:
1. The response rate (of the user sessions where this was shown, how many responded?)
2. The average response
3. The "net promoter score"

Net promoter score is calculated as follows: 
Responses [0,6] are considered "Detractors". Responses [7,8] are considered "Passives". Responses [9,10] are considered "Promoters". NPS is calculated as the percentage of responses that are "Promoters" minus the percentage of responses who are "Detractors". ("Passives" count toward the overall response denominator).

We want to have a running chart of each summary value, with a monthly interval.

We also want to ask qualitative followup questions:
1. What did Terra do to earn that score?
2. What would have to change for you to give it a higher score?

These should have a free-text answer. We need qualitative responses aggregated in such a way that monthly a member of the product team can review all responses and compile a report of themes and suggested actions.

Suggested implementation:
Create a UI widget to ask the question. Record the score in the Metrics Kowledgebase bigquery overseen by Alex. (so we can track it on our dashboard and compare to previous periods). Record information regarding when this question was asked in Thurloe.

**Comment by bradtaylor** [comment]
We may want to supply an integrated support solution like Intercom or Drift, so that we can help our intended Q3 onboardees out in real time (help make a good impression). I think they may already provide options to collect these sort of data? Can you look into that?

This is a shim while the user base is small while we consider intended long-term support solutions. We should discuss this with Geraldine.

**Comment by bradtaylor** [comment]
This is going to be handled via Zenhub. Work with Geraldine's team

**Comment by bradtaylor** [comment]
Now that comms has settled on Zendesk for managing their support issues and knowledgebase, investigate whether this provides out-of-the-box support for this sort of widget.

**Comment by bradtaylor** [comment]
Potentially blocked on Comms having Zendesk set up- I think it is, but we should check with Tiffany

**Comment by katevoss** [comment]
This is no longer blocked by #740. Note that we will need Zendesk to be set up with an account level of "Enterprise" or "Professional".

**Comment by bradtaylor** [comment]
Check with Kate N regarding our account level.

**Comment by bradtaylor** [comment]
Design for this can just be choosing colors over whatever standard modal they present.

**Comment by bradtaylor** [comment]
Need to choose when this is displayed

**Comment by knoblett** [comment]
We have an Enterprise level account, which means we can send out satisfaction surveys via email in response to tickets submitted via the in-app help. The email would look something like this:

![screen shot 2018-11-14 at 2 38 18 pm](https://user-images.githubusercontent.com/13629186/48507823-fd398880-e81a-11e8-9274-391b919e1b78.png)

NPS is a separate add-on which we do not pay for currently. We can pay for it, and it would allow us to send out emails like this:

![screen shot 2018-11-14 at 2 39 21 pm](https://user-images.githubusercontent.com/13629186/48507868-19d5c080-e81b-11e8-82e4-a642b6553681.png)

To my knowledge, neither of these are provided as a widget to plug into the app. However if you are interested in that, let me know and I can speak to our Zendesk contact to see what they can offer.

**Comment by bradtaylor** [comment]
@knoblett We would want this as a widget to plug in to the app, even if we had to roll our own, as we did in FireCloud. I'm surprised it isn't offered. Can you ask our Zendesk contact?

**Comment by bradtaylor** [comment]
Ideas in the room: 
It's unclear if Zendesk will support this. Looking unlikely. 
If we're rolling our own, we can set up a cloud function or service that listens to the response and loads it into the backend store of our choice (Alex's BQ dataset?)

**Comment by knoblett** [comment]
Absolutely. I've contacted Zendesk to find out.

**Comment by tmm211** [comment]
We used Survey Monkey's pop up widget in FireCloud. We could use the same in Terra. Let me know @bradtaylor . I also wonder if the widget would be smart enough to know if you had seen it in FC and therefore it won't show you again if you log-on to Terra

**Comment by zarsky-broad** [comment]
We're going to roll our own for maximum flexibility. Brett created https://terra-rex-dev.appspot.com/docs/ for this.

**Comment by knoblett** [comment]
I spoke with Zendesk support, and they do not have a pre-baked NPS widget. They did suggest that our developers could use the NPS API to build out a custom widget (like we did with the Contact us button). If you'd like to go that route, let me know.

**Comment by zarsky-broad** [comment]
@knoblett For the time being, the scores will be recorded in a database in google cloud. Since the Zendesk 'create a response' API requires a password to access, we can't call it directly from the UI, but we could forward responses to it from our custom service if we decide that we want to do that.
