### ISSUE TITLE
Notebook ipynb localization

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#35]
An analyst can edit/run their project notebook directly from Saturn, such that they avoid configuration, authentication, and billing makework

Click a notebook, and it automatically gets sent to the cluster for your workspace's project.
We should also localize a config file with some info about which workspace this ipynb came from

see the work CH has done for AoU:
https://docs.google.com/document/d/1GbaL1otgswBEOqfte8JO8uQDG_vSEG4a-qcKMEdufLI/edit?ts=5a9f0881#heading=h.vswboj30ycb7

**Comment by bradtaylor** [comment]
@rtitle @calbach @blrubenstein Can you comment on how this is being handled for All of Us?

**Comment by zarsky-broad** [comment]
Existing APIs should cover this.

**Comment by bradtaylor** [comment]
We can manually place an ipynb in /notebooks of the workspace bucket (using gsutil). This then is about displaying the contents of that dir as cards, and providing the interaction to click on a card and have it open on (what ought to be a single) cluster.

Right now we're allowing multiple clusters per user per project. In the future this will be a single cluster. I'm happy for now while things are multiple to just take the head of a list

**Comment by bradtaylor** [comment]
From @zarsky-broad : localize all ipynb files in workspace when you view that tab (have a little check when something is available to open). Then user clicks and it opens instantly.

**Comment by zarsky-broad** [comment]
Will eventually use https://github.com/DataBiosphere/leonardo/issues/306
