### ISSUE TITLE
Groups Management

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#351]
Saturn users need to share their workspaces and other resources with groups of users, in order to save time over adding individuals.

For technical reasons (pet service accounts and proxy groups), these must be groups that Saturn creates and manages via the Rawls groups APIs.

Users can be a member of a group, or an admin (meaning they can add/remove users)

Members need to view the groups they belong to, and what their role is.
Admins need to be able to:
* view the members of a group
* add new users
* remove existing users
* change the roles of other users (member <-> admin)

See designs in Invision here:
https://projects.invisionapp.com/d/main#/console/13746874/307724355/preview

**Comment by lstrano-broad** [comment]
New screens are up in Invision fo review
