### ISSUE TITLE
Notebook ipynb delocalization

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#36]
Notebook progress is persisted appropriately back to the Saturn Project.

To be achieved by syncing the ipynb file back to GCS.
See the work CH has put into All of Us:
https://docs.google.com/document/d/1GbaL1otgswBEOqfte8JO8uQDG_vSEG4a-qcKMEdufLI/edit?ts=5a9f0881#heading=h.vswboj30ycb7

**Comment by bradtaylor** [comment]
@rtitle @calbach @blrubenstein Can you comment on how this is being handled for All of Us?

**Comment by calbach** [comment]
I have an open PR to Leo for this feature: https://github.com/DataBiosphere/leonardo/pull/259. Saturn should be able to just use that directly.

**Comment by dmohs** [comment]
CH's PR was merged, so this is as easy as placing a .delocalize.json in the folder of the notebook file. See his code for details: https://github.com/DataBiosphere/leonardo/blob/develop/jupyter-docker/jupyter_delocalize.py#L10

**Comment by zarsky-broad** [comment]
Blocked by https://github.com/DataBiosphere/leonardo/issues/307
