### ISSUE TITLE
Add security scanning and assessment

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#368]
We are documenting a process for security scanning and assessment process to Saturn development (see SDLC document #367). Work with Albano to implement our intended process

**Comment by bradtaylor** [comment]
We already do this with sourceclear (Bernick set it up). Confirm with Bernick/Albano that this is all we have to do (and make sure it's written in the SDLC).

**Comment by zarsky-broad** [comment]
Seems like the fact that we're tracking javascript errors [here](https://rpm.newrelic.com/accounts/1862859/browser/132130567/js_errors) is sufficient, as long as someone is actually monitoring it.
