### ISSUE TITLE
Improved notebook cluster creation

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#37]
An analyst can enter their project and open a notebook without explicitly requesting their cluster be created, so as to avoid the subsequent 5-15min initialization time.

One approach here is to hide cluster creation to occur the first time a user is added to a Project in a particular billing project, pausing the cluster as soon as it's been created (unpause is a matter of a second or so)

**Comment by dmohs** [comment]
Blocked by: https://github.com/DataBiosphere/leonardo/issues/131

**Comment by dmohs** [comment]
Proposed implementation:
On sign-in,
1. GET https://rawls.dsde-prod.broadinstitute.org/api/user/billing
2. GET https://notebooks.firecloud.org/api/clusters?includeDeleted=false

For any project that exists in (1) with a creation status of Ready and does not appear in (2), create a cluster using that project.

**Comment by bradtaylor** [comment]
Cluster should be n1-standard with 500G disk and 0 workers (ie no additional spark stuff).

**Comment by bradtaylor** [comment]
David brought up the idea of keeping the app codebase simple by putting the logic from his comment in a cloud function

**Comment by MattPutnam** [comment]
This is blocked on a Leo issue. It's causing problems to create a cluster and immediately stop it; the cluster needs time to finish initialization before it can be stopped. Leo team is considering options, the initial thing will probably be for Leo to return 409 when attempting to start/stop before initialization completes. Long term, there should be an endpoint for "create-and-then-stop" (or "create-in-stopped-state").

**Comment by kleighwe** [comment]
@MattPutnam I'll check in with @blrubenstein and @rtitle on a timeline for this. Bru or Rob- can you link the blocker when you create the ticket? I'll find you for facetalking soon as well.

**Comment by rtitle** [comment]
Hello, I'm tracking this in 2 Leo tickets:

1. Make API return 409 Conflict where appropriate: https://github.com/DataBiosphere/leonardo/issues/247

2. Add "create in stopped status" endpoint: https://github.com/DataBiosphere/leonardo/issues/311

**Comment by rtitle** [comment]
Update: Issue 247 above is merged to Dev and 311 is in PR.

**Comment by rtitle** [comment]
Issue 311 is now merged to dev.
