### ISSUE TITLE
Improved notebooks cluster management

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#38]
An analyst can control the power of their compute environment so as to make tradeoffs between cost and power, without having to manage their own VMs directly. 

Needs visual design.
Probably worth it to validate our mocks before implementing
"wireframes+" interaction + viz design for controls providing the ability to:
* view the cost of their compute
* play/pause/stop their compute
* up/downsize their compute (including adding/removing spark workers)

Many of the actual controls are currently in the firecloud UI. It's about presenting them in a different way. One could have a 'runtime' element somewhere in the UI with a play/pause/stop button, the cost, and an up/downsize icon that opened up a form for specifying the size of runtime compute.

Needs eng design:
Some of the things we want to do (pause/unpause) have endpoints in leo
Up and downsizing the compute does not. For adding/removing spark workers, this can be done on the existing cluster. For changing the machine type (CPU/RAM) of the master/worker VMs, that will involve destroying the cluster and adding a new one. I think the best thing to do here is to warn the user that this is slow, snapshot the disk, create the new cluster, load the old disk (so the environment carries over) and then destroy the old cluster. We can put up a spinner for the 5min wait time.

External dependency:
Will likely need backend work from the leonardo team

## Visual Design
https://projects.invisionapp.com/d/main#/console/13746874/286853469/preview

## Eng Design
For this MVP, we will only consider up to two of the most recently created clusters (by createdDate in the Leo response). The states are:
- one cluster, status "Creating" => cluster not ready
- two clusters, one with status "Creating" => preparing new cluster (poll for changes)
- two clusters, both with status "Ready" => new cluster ready
- one cluster, status "Ready" => normal state

Leo does not appear to support adding/removing workers, but this should be tested by attempting to "create" an existing cluster with different values.

The UI needs only to create the new cluster when prompted by the user and display the status as specified above. The "current cluster" is the least recently created with a status of "Ready." On the user's action, the current cluster is deleted causing the new cluster to immediately become the current cluster.

**Comment by bradtaylor** [comment]
We could break this ticket up and only do cost + play/pause now while we wait for the backend work on replacing a cluster

**Comment by kleighwe** [comment]
Designs in Invision!

**Comment by kleighwe** [comment]
@bradtaylor    will clarify some additional questions with Lou/Marty RE placement of widget

**Comment by bradtaylor** [comment]
We're going to place the widget directly to the left of the user profile at the top level of nav, for now. We can revisit where on the page it lives with Marty + Lou once we actually get the thing in there
