### ISSUE TITLE
Restyle data tab

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/saturn-ui#386]
https://projects.invisionapp.com/d/main#/console/13746874/286545631/preview
New visual styles have been loaded in Invision for the data tab. Refresh the styles on this tab. If an existing feature is not in the wires (download buttons), check with design or @zarsky-broad 

Where new functionality is indicated, ignore it for now.

**Comment by bradtaylor** [comment]
Break out separate stories for:
column resize 
column selector
deleting reference datasets
deleting individual global attributes
