### ISSUE TITLE
Sign in then sign out before cluster creation results in cluster creation error messages

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#406]
Minor: 
It would be nice if it could detect that the user was signed out so that it doesn't show this message.

![Screen Shot 2018-07-22 at 11.50.57 PM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/dc2f454d-d01a-46e3-b2ac-1c7de4682b2b)

**Comment by bradtaylor** [comment]
One idea: refresh the page on signout.

**Comment by bradtaylor** [comment]
This should not happen anymore, due to other recent improvements. We will reopen if this recurs
