### ISSUE TITLE
Usability: Labels (or at least alt text) for buttons

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#407]
I was looking specifically at the clone workspace button, since it's got the "copy" icon, which is close but not an exact match in this case. It would be useful for users not familiar with the application to be able to read what the buttons will do before clicking them.

This site recommends adding labels to all buttons: https://axesslab.com/icons-ruining-interfaces/

I'd be interested in learning what others think about this.

**Comment by dmohs** [comment]
I agree that all buttons should have labels by default.
