### ISSUE TITLE
Better error messaging when a notebook cannot be found

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#408]
This seems to be valid behavior, but it may help the user to resolve their issue.

In this case, I created the problem by renaming the notebook file from within Jupyter. Then tried to open the notebook. It tries 5 times then errors. I think it would be helpful for the user if we provided information like "The file <name> cannot be found (did you rename it?)"

![Screen Shot 2018-07-18 at 5.05.09 PM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/5c58ef7c-e59f-4361-a755-21ca7a475227)

**Comment by bradtaylor** [comment]
Fix the error message and clean up the retry while we are there
