### ISSUE TITLE
Rename default branch to "master?"

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#412]
When we started this project, we envisioned a "git flow" type model where development occurs on the "dev" branch and releases are based off of different branches. Instead, we have converged on a process where all commits go into one branch and releases are controlled elsewhere. In most repos, this branch is called "master," but in ours it's called "dev." Renaming this branch to "master" might remove a potential point of confusion for new developers.

**Comment by bradtaylor** [comment]
Team has decided not to pursue this.
