### ISSUE TITLE
Add a column selector to the Data tab data tables

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#417]
In the data tab, tables may contain many columns. Add a column-selector widget. See the gear affordance on the Invision mocks:
https://projects.invisionapp.com/d/main#/console/13746874/286545631/preview

Clicking this should bring up a widget where a user can select which columns are displayed, including all/none, reset their selection, or drag columns to change their ordering. Here is FireCloud's:
![Screen Shot 2018-07-23 at 10.17.59 PM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/534ba5ac-7280-4af9-9c27-f88255d3f5dd)

Column selections should be persisted in state history while you are on the current page, otherwise it resets.

Users should also have an option to sort columns alphabetically. FireCloud app is doing this:
https://github.com/DataBiosphere/firecloud-app/issues/129

**Comment by dmohs** [comment]
Where to store this state is an important point for discussion. Browser local storage is convenient, but changing the schema requires a fairly sophisticated versioning system. This may be better served by first-class state in Rawls, which can respect relational integrity (the preference is deleted when a workspace is deleted, for example).

**Comment by panentheos** [comment]
Implementation note: We should use `react-sortable-hoc` to make the list sortable.
