### ISSUE TITLE
Add/Delete individual global variables

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#421]
Global variables is your place to stick extra bits of information you might need in your workflows. We're only intending to have one table of them, but that table should be modifiable. 

Users should have the ability to add a new key:value pair and set the type of the value (see FireCloud for the list of available types). Users should also have the ability to remove one or more rows. Removing row(s) should trigger an 'are you sure' confirmation.

Only workspace WRITERs or OWNERs should be able to perform these actions. Otherwise the affordances should be greyed out with the message (as hovertext) "You do not have access modify data in this workspace." Note- we're going to put a link here to request access. Separate story.

**Comment by martygardner** [comment]
Interaction design for this is shown in the [rolling UX deck](https://docs.google.com/presentation/d/1-JQd63YQZmKLGPSgvSjRXot8OlFmP3r3D2EaEdgYIyE/edit#slide=id.g3fe0cc06a9_1_129) and approved by Brad. See speaker notes for details.
