### ISSUE TITLE
Optionally populate workflow parameters from an inputs json

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#422]
There now exist APIs for populating parameter bindings in Rawls method configurations (which we display as workflows) from a Cromwell inputs json file.

Add a small "Populate with a .json file" link above the input bindings table. This should have an info icon next to it with the text "You can either change the inputs/outputs below or upload a pre-populated .json file. After upload you can always edit manually. _Learn more about the expected format_" where the last sentence is a link to https://software.broadinstitute.org/wdl/documentation/inputs.php

Clicking the "populate" link should bring up a file selector. See FireCloud:
![Screen Shot 2018-07-23 at 11.27.37 PM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/56b23852-0eb5-4679-b06e-db2c97bfff6c)

Note, only WRITERs and OWNERs should be able to do this. Otherwise it should be not be shown (we don't have to worry about requesting access here, the launch button ought to take care of that)

**Comment by lstrano-broad** [comment]
Brad - Let's discuss when you get back from vacation.

**Comment by bradtaylor** [comment]
We did end up doing this story. But we might want to spiff up the design with an icon. Low priority

**Comment by bradtaylor** [comment]
This seems like it's done
