### ISSUE TITLE
Hide optional workflow inputs/outputs by default

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#423]
The list of workflow inputs can be large. This is especially true when a workflow includes many rarely-used optional inputs, as is the case for GATK workflows. Hide these by default and provide a nice obvious "Show optional inputs" affordance. When optional inputs are shown, this should change to "Hide optional inputs". If an optional input has been given a value, it should be shown regardless.

The same behavior should apply to optional outputs.

Any workspace user should be able to perform this show/hide, regardless of access level. Note, it doesn't have to be global for everyone.

**Comment by martygardner** [comment]
The design solution for this is part of the larger revamp of method config [illustrated in the Oct 2 UX deck update](https://docs.google.com/presentation/d/1-JQd63YQZmKLGPSgvSjRXot8OlFmP3r3D2EaEdgYIyE/edit#slide=id.g36b150069c_1_0).

![image](https://user-images.githubusercontent.com/33694045/46555147-6ccd6700-c8b0-11e8-86e6-4cb0e2a06430.png)

**Comment by bradtaylor** [comment]
Lou has a mock based on the above. The affordance is "advanced settings" and should be collapsed by default.
https://projects.invisionapp.com/d/main#/console/13746874/326795248/preview

**Comment by katevoss** [comment]
To clarify the UX: when a user clicks "Show optional inputs/outputs", the optional in/outputs will be displayed in the same table as the required in/outputs, below the required inputs/outputs. Then the user can click "Hide optional inputs/outputs" and the optional items are hidden. 

@bradtaylor this is the current plan, unless you advise otherwise

**Comment by katevoss** [comment]
Discussion topic: as far as I know, all output values are optional. Today all outputs are marked as "Required", which is not true. I can file a ticket to fix this, it should be a small change.

In discussion with Brad, he said that we should show all Outputs by default. Therefore this button to "Show optional inputs" would be limited to the inputs page.

**Comment by katevoss** [comment]
More fodder for the discussion: @aednichols explained that there is no concept of Optional Outputs in WDL, [yet (click for WDL issue)](https://github.com/openwdl/wdl/issues/20). If a user specifies outputs, then the outputs will be written to the data model. If the user does not specify outputs, then the outputs will not be written to the data model. HOWEVER in both situations the user is still doing an analysis which takes time and more importantly, costs them money. 

I think that we should continue to allow users to include outputs or not, which effectively makes them optional. This is the current behavior in Terra. I think if a user doesn't specify outputs that we should have a message telling them that the outputs will not be in the data model, and they will need to look in their Google Bucket for their outputs. 

This ties in with discussions that @bradtaylor and @panentheos are currently having regarding sensible defaults.
