### ISSUE TITLE
JupyterLab

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#425]
Provide users the option of opening their saved notebooks in [JupyterLab](https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906), the next evolution of the jupyter UX. JupyterLab offers a richer experience more akin to Rstudio or an IDE (though not exactly the same as either).

Offer users the option of opening their notebooks using Lab, vs the base UX. Azure notebooks has a nice toggle button to this effect.
<img width="1260" alt="screenshot 2018-08-02 20 03 47" src="https://user-images.githubusercontent.com/3492466/43731356-34b9a9ea-997c-11e8-946e-55555fe5fdcb.png">

We still want to ensure that notebooks are being auto-sync'd to the workspace. We want the notebooks list to appear in the workspace. This may have to wait until the following issue is resolved with Leo:
https://github.com/DataBiosphere/leonardo/issues/474

**Comment by seanhorgan** [comment]
Any reason why jupyterlab wouldn't be the default notebook solution over regular jupyter?

**Comment by bradtaylor** [comment]
Implementation (not design!) blocked on the Leo dependency

**Comment by martygardner** [comment]
Proposed interaction flows for 1) opening a notebook once in JupyterLabs, and also 2) always specifying the preference to use JupyterLabs for opening notebooks, are in the [rolling UX deck](https://docs.google.com/presentation/d/1-JQd63YQZmKLGPSgvSjRXot8OlFmP3r3D2EaEdgYIyE/edit#slide=id.g3382bde459_1_53).

**Comment by lstrano-broad** [comment]
![1.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/c9ebf069-bb75-4d1d-a205-127fce35c279)![2.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/95547d41-f591-4bf3-877f-373057005072)![3.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/437ca825-37b5-44d8-a43a-6443e0b2b0fb)![4.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/a869287e-67ad-4cec-9e62-d4f9436b18b0)

**Comment by lstrano-broad** [comment]
![2.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/03abb12f-6f62-4a63-baca-c4d8fc24f70c)

**Comment by lstrano-broad** [comment]
![3.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/44c32a33-75bf-417c-9bac-4f3b80d252fe)

Updated left hand nav showing Settings link

**Comment by lstrano-broad** [comment]
![4.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/193fff34-6721-49a5-b945-fc924232eea1)

New Settings page

All new screens uploaded to Invision... Start with "Workspace Dashboard" screen to see interaction

**Comment by bradtaylor** [comment]
Removing blocked label
Nothing impeding https://github.com/DataBiosphere/leonardo/issues/474 seems like it should be an issue for us.

We will handle the extension for lab separately

**Comment by bradtaylor** [comment]
Unblocked because jupyter lab released by leo. Still don't have extensions- just open Lab up in a new tab

**Comment by bradtaylor** [comment]
Any idea when this issue will be approved for release?

**Comment by elizzhao** [comment]
Add disclaimer that autosave interval is 2minutes (while regular notebooks is 5s) and that closing without saving in that fairly long interval will cause lost work!

**Comment by mbookman** [comment]
Hi @elizzhao!

Can you add a comment here when closing the issue?
Is JupyterLab implemented?
What should users expect?

Thanks.

**Comment by elizzhao** [comment]
Sure!

Users now have the ability to open a notebook in JupyterLab from the three-card menu by choosing the "Open in JupyterLab" selection. 

One major difference between JupyterLab and Notebooks is that lab currently autosaves every two minutes, while we have notebooks auto-saving every 5s. There's a warning that appears when using Lab that lets the user know of this difference, and to be careful to ensure they have saved before closing the notebook.  

The Notebooks Team has also recently released extensions, so we'll be working to add that to Terra in the near future, but that is not currently in Terra.

**Comment by mbookman** [comment]
Thanks. Is this in production? I don't see the option.

**Comment by elizzhao** [comment]
Not yet, it should be out on prod tomorrow morning!
