### ISSUE TITLE
Allow Saturn users an affordance to find WDL from Dockstore and the FireCloud methods repo

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#430]
Users of saturn need to be able to find WDL workflows for use on their data. (Eventually we will provide search on other artifacts such as pre-built analysis workspaces and notebooks, but those are separate tickets.)

There are two Saturn-connected workflow repositories at the moment.  The first is Dockstore. The second is the FireCloud methods repository.

Supporting dockstore is achieved by providing a link to https://dockstore.org/workflows
alongside the following instructional text:

> ## Find WDL workflows from Dockstore
> Browse publicly available WDL workflows in Dockstore. From your workflow of interest, look for the "Launch with FireCloud" button to send it to a workspace. Workflows imported into FireCloud may be used from Saturn.
> ![screen shot 2018-09-17 at 1 34 25 pm](https://user-images.githubusercontent.com/3492466/45639503-2ee1dd80-ba7e-11e8-912b-0e51865a7178.png)

There will be a separate ticket to point Dockstore to Saturn rather than FireCloud, at which point we can update the instructional text.

Supporting the FireCloud methods repository means providing a link to https://portal.firecloud.org/#methods, alongside the following instructional text:

> ## Find WDL workflows from the FireCloud Methods Repository
> Browse WDL workflows in the FireCloud Methods Repository. From your workflow of interest, look for the "Export to Workspace" button to send it to a workspace. Workflows and configurations imported into a FireCloud workspace may be used from Saturn.

These options should be available as part of code exploration from the lefthand nav. Replace 'find code - coming soon' with "Explore tools" and the telescope icon from Invision:
https://projects.invisionapp.com/d/main#/console/13746874/286545633/preview

"Explore tools" should present both of the above options.

There should be an info icon (i) with a message "Search workflows in Dockstore. Use the "Launch with FireCloud" button to send a workflow to your workspace"

While you are in the neighborhood, change "Workspaces" to "See All Workspaces" in the hamburger menu to match designs

**Comment by bradtaylor** [comment]
Spoke with Lou a bit. His inclination was to make these two options available as suboptions from the top-level nav and not include the explanatory text. I'm fine with that- the explanatory text is not a hard requirement. Just wanted to note that since this has appropriately moved to interaction design with Marty.

Ultimately, the job to be done is that people have to find and visit these links, identify content they want, and send that content to their workspace. The latter two stages of that journey happen outside of our main app. However design wants to structure things to support that objective is good with me.

**Comment by lstrano-broad** [comment]
Updated screens in Invision - view Library screens...
https://projects.invisionapp.com/d/main#/console/13746874/331592848/preview
