### ISSUE TITLE
Edit workspace descriptions and save them

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#454]
Allow users to edit their workspace descriptions, and save these. Users should be able to bold things, highlight them, create numbered or bulleted lists, and potentially other presentation features.

One option for editing is Markdown. If we choose this, we should have a toggle option for preview mode, but don't have to support a threeway view. Github does a nice job here. The convenience buttons for bold, italic, etc are nice to have.
![Screen Shot 2018-07-30 at 10.43.26 AM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/4b8b436f-0c24-491b-80eb-bbca3bc22b12)

**Comment by martygardner** [comment]
@bradtaylor @zarsky-broad Is Markdown format our requirement because it's the right tool for the user audience -- that our users will naturally think in code syntax to write their descriptions -- or is it just easy to build? If there was a non-Markdown wysiwyg editor driven by a library available at the same development cost as Markdown supported only by writing the native syntax, which would we choose?

**Comment by zarsky-broad** [comment]
I defer to @bradtaylor on this -- we've historically used Markdown in Firecloud.

**Comment by bradtaylor** [comment]
@martygardner Great question. This is probably FireCloud goggles, as Isaac suggests. This is complicated, because we have several different user archetypes. Tool developers and some of the more technically savvy analysts probably are used to markdown (especially from GitHub). Some researchers are used to coding text from LaTex, though most journals seem to want Word docs (!).

But Project Managers do not expect markdown. Even folks like Fran's team probably don't want to write markdown. In practice, I don't see markdown get used that often. So a wysiwyg editor is probably preferable

**Comment by bradtaylor** [comment]
I've updated the description here to deemphasize markdown as the solution

**Comment by lstrano-broad** [comment]
![Screen Shot 2018-08-10 at 11.47.35 AM.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/64076c18-1a1d-4d29-9d00-8761aacb4e1d)

**Comment by lstrano-broad** [comment]
New screens up in Invision. I'm assuming what we would want as a WYSIWYG styling options, feel free to pare down if need be

**Comment by dmohs** [comment]
There is an old argument I'm going to bring up here, which is that markup-based editing shifts the author to focus on prose rather than formatting—the correct focus for writing documentation. This may be a reason to encourage less-tech-savvy people to embrace Markdown.

**Comment by martygardner** [comment]
I might suggest that starting with a limited set of styling options like,
bold, italic, bulleting, a single subhead style, and maybe links, would
give people enough semantic tools to organize their material. And we
consciously rule out left/right/center alignment, open-ended type sizes,
faces and colors, and other tools likely to lead to visual mayhem.

Just generally making all formatting hard seems user-unfriendly.

**Comment by zarsky-broad** [comment]
We're leaning towards using https://simplemde.com
