### ISSUE TITLE
Add Cohort Name text field to import-data

### ISSUE THREAD

**Issue by melissachang** [DataBiosphere/saturn-ui#455]
Here's the flow I'm picturing:
- User selects cohort in Data Explorer, let's say [African females with high coverage](https://test-data-explorer.appspot.com/)
- User clicks Export to Saturn button. This JSON is sent to import-data:
```
   { 
     "entityType": "cohort",
     "attributes": {
       "query": "SELECT Sample FROM `genomics-public-data.1000_genomes.sample_info`
WHERE Gender = "female" AND Super_Population_Description = "African" AND X_Targets_Covered_to_20x_or_greater > .9",
       "size": 187
     }
   }
```
- import-data detects cohort entityType and displays a Cohort Name text field
- User types "African female high coverage"
- User clicks Import. Final JSON sent to rawls:
```
   { 
     "name": "African female high coverage",
     "entityType": "cohort",
     "attributes": {
       "query": "SELECT Sample FROM `genomics-public-data.1000_genomes.sample_info`
WHERE Gender = "female" AND Super_Population_Description = "African" AND X_Targets_Covered_to_20x_or_greater > .9",
       "size": 187
     }
   }
```

WDYT @bradtaylor @dmohs @alahwa

**Comment by bradtaylor** [comment]
I like the ability to name the thing. In this case I still think we're prototyping some of these data flows from our DE, HCA Orange Box, Boarwalk and Windmill, others. In many other cases the primary entity is a sample or something and they already have sample names. In that case, asking us to name it doesn't make sense.

I think we can make this work well for now by having the popup show up on the Data Explorer side. If we don't like it as a popup it can be a persistent text entry next to the send button. Then, DE sends us the fully-configured JSON (your second blob).

This puts the DE fully in control of what is sent and Saturn in control of where that thing is put.

If this cohort pattern does end up being a durable pattern, and gets used for future projects, we can move this functionality over the fence to Saturn itself.

Thoughts?

**Comment by melissachang** [comment]
SG, just one question -- For example in the Team Calcium demo, 1 participant/48 samples were imported from Windmill (female African Americans). Do you think users will want to create additional cohorts in the same workspace (eg male African Americans), and kick off workflows for a cohort (eg only female African Americans)?

**Comment by melissachang** [comment]
We'll do the dialog
