### ISSUE TITLE
Notebook open error messaging could be clearer

### ISSUE THREAD

**Issue by calbach** [DataBiosphere/saturn-ui#463]
Specifically in the case where I have 0 clusters and I click to open a notebook. On the Saturn notebook loading page I initially thought there was a transient error given the generic error messaging. Later I noticed the "details" section, which told me I had 0 clusters. It seems like this particular error could be surfaced more clearly and made to look less like a transient backend error, or alternatively the user should be put into a flow where they are asked to first create a cluster when they attempt to open a notebook sans cluster.

**Comment by bradtaylor** [comment]
For the case where the 0 cluster state is due to the (valid!) situation in which you don't have write access to a workspace in the billing project, we should have a good explanatory message
