### ISSUE TITLE
'open terminal' does not warn the user when leaving a notebook not yet autosaved

### ISSUE THREAD

**Issue by deflaux** [DataBiosphere/saturn-ui#470]
To reproduce:
1. open an existing notebook
1. make a few changes that have not yet been autosaved
1. click on the Saturn 'open terminal' icon
1. click the back button in the browser
1. notice that the changes are gone

Instead, perhaps open the same 'Leave site?' dialog box users see when clicking on the Jupyter icon to navigate to the terminal using the Jupyter UI.

**Comment by zarsky-broad** [comment]
The tough thing here is that since the notebook is in an iframe, we don't have an easy way to know if there's something unsaved. We might be able to use a plugin, though, we'll have to look into that.

**Comment by bradtaylor** [comment]
Isaac says it is possible using a plugin. It can send this information up through the iframe to the parent.

**Comment by bradtaylor** [comment]
Another option, that may be less complicated in the nearterm: Tune the autosave interval to something small (5s?)

**Comment by bradtaylor** [comment]
Option2 is "exponentially easier". @deflaux I'm inclined to do this for now. After we make this change, can you let us know if you continue to hit these instances of lost work, and how frequently?

**Comment by pgrosu** [comment]
Just create a non-standard attribute for the iframe to update (i.e. `isSaved`) or embed it in the `name` attribute.

**Comment by zarsky-broad** [comment]
@pgrosu is there a way to do that for cross-origin frames?

**Comment by pgrosu** [comment]
@zarsky-broad Sure, why not use `postMessage()`?  Here's a tutorial:  [https://www.viget.com/articles/using-javascript-postmessage-to-talk-to-iframes/](https://www.viget.com/articles/using-javascript-postmessage-to-talk-to-iframes/)

**Comment by zarsky-broad** [comment]
Yes, that's what we'd been considering, we'd just have to write a jupyter plugin to do it.

**Comment by pgrosu** [comment]
Cool :)

**Comment by zarsky-broad** [comment]
According to [this](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/savewidget.js#L159) it looks like the most reliable way to track something like the saved state of a notebook is just to watch the element on the page.

**Comment by bradtaylor** [comment]
We are tuning down the autosaved interval as #491

**Comment by deflaux** [comment]
This issue has gotten a bit worse now with the updates to the Saturn UI around Leonardo. I'm losing work more often since there are more ways to leave the current page and not notice that autosave has not occurred. A colleague also lost work recently.

To work around this for now, how do we get back to the normal Jupyter front door? The clickable Jupyter icon has been covered up by the Saturn header.

**Comment by bradtaylor** [comment]
We are going to restoe the jupyter header line immediately, so that saved status is displayed.

Spike for adding nav warnings is #633

**Comment by kleighwe** [comment]
When navigating away from the page, we should automatically trigger a manual save.

**Comment by bradtaylor** [comment]
It may be possible to actually trigger a save on nav-away rather than attempt to warn/prevent nav-away, which technically led to some corner cases. This seems like a better experience anyway as it should prevent lost work. Do you agree, @deflaux ?
