### ISSUE TITLE
uploading a ipynb file in html format fails

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#478]
Potential bug -- found while perusing with Mohs.

Uploading a recent json ipynb file works, but a ipynb file (that I downloaded a couple weeks ago when testing Saturn) fails. 

Side note: Would it also be worth making the error message more informative for this general case where a json is expected but html is received? It probably could happen elsewhere in the app.

![Screen Shot 2018-08-03 at 9.48.57 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/5b774b91-52c6-47a5-9294-d52a709c4d3c)

**Comment by bradtaylor** [comment]
The error here should be changed to something indicating that the ipynb format appears to be invalid

**Comment by zarsky-broad** [comment]
@panentheos sez: create a utility to attempt to parse JSON and throw a nice error message if it fails
