### ISSUE TITLE
implement account choose for the profile page

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#479]
Found with Mohs

Also, the `i` button / hitbox is tiny. Recommend making it a bit bigger. 

![Screen Shot 2018-08-03 at 9.53.52 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/5ee44d09-43a2-43e5-a573-5f2a959bf9fd)

**Comment by dmohs** [comment]
Has this been discussed? I'm not sure exactly what this means.
