### ISSUE TITLE
The error banner makes actions at the top of the page inaccessible. 

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#481]
![Screen Shot 2018-08-03 at 11.21.06 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/083b6339-dfa6-4f7b-b731-624dc0c09874)

The user would not be able to click on the workspace, hamburger menu, cluster dropdown, or other objects.
![Screen Shot 2018-08-03 at 11.21.48 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/46e9aac5-4018-46eb-ad38-4b9e8d201419)

**Comment by dmohs** [comment]
If the behavior we want is to allow the user to navigate without dismissing the error, one solution would be to add padding to the top of the page when an error is displayed so the user can access navigation items by scrolling. This often involves adjusting the scroll position as well to avoid a jump.

**Comment by bradtaylor** [comment]
I'm not convinced this is the behavior we want though. We do want the user to notice the error (it's pretty noticeable. And there's a dismiss (x) icon right there.

Thoughts? @lstrano-broad?

**Comment by bradtaylor** [comment]
In Refinement, team feels like it is sufficient to make the dismiss icon more obvious (larger perhaps. Moving it to the left to be adjacent to all the other content). Interested in design opinions

**Comment by lstrano-broad** [comment]
On it - will provide a mock for this behavior

**Comment by lstrano-broad** [comment]
![Screen Shot 2018-08-10 at 10.55.35 AM.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/38d4c142-48b0-4a74-8106-170f5ced96ce)

**Comment by lstrano-broad** [comment]
New banner treatment up in Invision...
