### ISSUE TITLE
Change the text when starting up a notebook

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#487]
Currently, when user opens a notebook, we have a couple status messages:
<img width="332" alt="screen shot 2018-08-06 at 12 43 05 pm" src="https://user-images.githubusercontent.com/3492466/43729413-33e691fa-9976-11e8-89df-424c2b99fe20.png">

User reports "This screen is a little scary because waiting for cluster to start makes me think I’m spinning up a new expensive cluster each time I click the notebook button (maybe I am, so that’s fine) and because copying notebook to cluster doesn’t actually make sense unless you understand that the notebook is saved somewhere other than the cluster "
We don't talk about clusters elsewhere in the app, we talk about the 'notebooks runtime'.
Replace the text of the above messages with the following
"Waiting for notebooks runtime to be ready"
"Loading notebook"

**Comment by dmohs** [comment]
Suggest: "Waiting for notebooks runtime to be ready..." since we won't actually be unpausing it if it is already running.

**Comment by bradtaylor** [comment]
Suggestion accepted
