### ISSUE TITLE
Add a list view to the tools tab

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#488]
Everywhere else we have a card view, we have a list view. Do the same thing for the tools tab. Some users have many tools. Include the icon
<img width="135" alt="screen shot 2018-08-06 at 12 46 24 pm" src="https://user-images.githubusercontent.com/3492466/43729561-a81ec2fe-9976-11e8-8335-763a92bbdc17.png">

**Comment by lstrano-broad** [comment]
New screens up in Invision...
![Screen Shot 2018-09-09 at 9.38.39 PM.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/6f5e7aa5-7c73-41ca-8c7c-62920289ae4a)

**Comment by katevoss** [comment]
Currently we don't have give the user the ability to Import a tool via Saturn, on FireCloud. I'm assuming that will be added later? @bradtaylor
