### ISSUE TITLE
Edit existing global variables

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#490]
Users should be able to edit and save their existing workspace global variables. Can we borrow the design from editing tool inputs?

**Comment by lstrano-broad** [comment]
Related to #421

**Comment by bradtaylor** [comment]
This is complicated somewhat as the user must suggest a type. Either string, number, boolean, or list of x (where x is one of preceding)

**Comment by martygardner** [comment]
Interaction design for this is shown in the [rolling UX deck](https://docs.google.com/presentation/d/1-JQd63YQZmKLGPSgvSjRXot8OlFmP3r3D2EaEdgYIyE/edit#slide=id.g3fe0cc06a9_1_129)
