### ISSUE TITLE
Increase the usable area for notebooks

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#491]
Multiple users have noted:
[When running notebooks] A lot of the screen is taken up Saturn and ipython banners leaving very little real estate for notebook code or outputs (plots)
![Screen Shot 2018-08-06 at 12.54.44 PM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/78b8747f-aa10-4c8a-b8c5-362071c27260)

Decreasing the size of the page footer seems like one obvious area to save room

**Comment by mbookman** [comment]
Could we get a "pop-out" link of some sort such that I can just run Jupyter outside of the Saturn framing? I have been right click on the jupyter icon and copying the link address... and pasting it into a new window.

**Comment by lstrano-broad** [comment]
Hold that thought Matt. I have a couple of ideas that I want to run by Marty @ Verily

**Comment by martygardner** [comment]
The original design had only one header row where the current code has three. It did this by removing the workspace section tabs -- Data, Tools, etc -- and relied on the breadcrumbs and a Close X to get back. And it also didn't have a separate Jupyter branding row.
![image](https://user-images.githubusercontent.com/33694045/43859922-0b806bfe-9b20-11e8-888c-0ec36a51415d.png)

If we have the ability to suppress / consolidate rows like this, it would be more space-efficient while staying integrated within the Saturn experience. @bradtaylor @dmohs Curious if this has been ruled out. 

If the Jupyter experience has to be shown entirely in its full native form, we might be better off just opening notebooks in new tabs.

Lastly, I do not think we should be taking space for the Saturn footer on every screen. This seems appropriate on the top screen/s, but not down in the details. This would save yet more space.

**Comment by bradtaylor** [comment]
It has not been ruled out. I think we just got our wires crossed here. Now that we have the ability to iframe, constructing experiences like this is possible. I want it to be possible to get back to the notebooks list. We've gotten feedback that doing that currently is unclear, so having the 'close X' is a good solution! It also allows us to get rid of the ws tabs currently taking up space.

I'm pretty sure we can also suppress the jupyter branding row. Unfortunately, the autosave notification shows up on this row. I wonder if it would be possible to catch this and put it somewhere else.

Putting the 'close X' next to the file | edit | view... menu might require a jupyter extension. It should be possible. But it would be easier to put it up near the notebook name in the breadcrumb up top, or somewhere like that. What do you think @martygardner ?

I totally agree the footer doesn't need to be everywhere.

I like this overall approach. Thanks Marty!

**Comment by bradtaylor** [comment]
The bottom banner will be removed by #573 
Here, we wish to remove the Dashboard|Notebooks|Data etc tabs, as well as the Jupyter logo layer.
We also wish to add an (x) icon to close the notebook, returning you to the notebook list.

Reduce the autosave interval on jupyter down to 5s, such that the lack of an explicit message saying "(autosaved)" is not problematic.

The 'File -> close' affordance in the base jupyter UX should be disabled.

**Comment by zarsky-broad** [comment]
Blocked by https://github.com/DataBiosphere/leonardo/issues/555
