### ISSUE TITLE
Launch analysis modal: Change the way a row is selected.

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#492]
Users have to choose a table entry (like a sample or a sample-set) to run their workflow against. Currently users have to select the first column text to choose the row. This is confusing and a bit restrictive.

User testimonial:
"In this particular screen shot `pair_id` is colored similarly to any other file type so when I click on it I expected it to open some kind of file details thing but instead it selected the row. I also really really wanted to click on any part of a row (outside of the blue text stuff) to select a row.  For a while I thought once I selected a row I had to hit `cancel` to select change it."

Ultimately, we're going to offer multi-selection. When this comes, it might involve checkboxes. We could do radio buttons for now. We could also potentially enable the case where clicking anywhere in a row selects is, as the user asks for (ie, clicking anywhere in the row can highlight it and check the checkbox). Looking for design opinions there. Users have this 'click anywhere in the row to select it' behavior in FireCloud.

**Comment by martygardner** [comment]
The design solution for this is part of the larger revamp of method config [illustrated in the Oct 2 UX deck update](https://docs.google.com/presentation/d/1-JQd63YQZmKLGPSgvSjRXot8OlFmP3r3D2EaEdgYIyE/edit#slide=id.g36b150069c_1_0).

![image](https://user-images.githubusercontent.com/33694045/46554801-668abb00-c8af-11e8-8d86-c659950f54a2.png)

**Comment by bradtaylor** [comment]
We're close enough to checkbox selection that this is not needed.
