### ISSUE TITLE
Include app identifier in http header

### ISSUE THREAD

**Issue by kcibul** [DataBiosphere/saturn-ui#499]
In order to enable our usage analytics to distinguish between different client applications, we need to include an application identifier as an http header in all calls to the workbench APIs.

To be coordinated with [AoU RW ticket](https://precisionmedicineinitiative.atlassian.net/browse/RW-574) so that we use the same header name, and consistent values

**Comment by dvoet** [comment]
is it required that it is a header? What should happen if it is not included?

**Comment by bradtaylor** [comment]
This is awaiting some broader discussion over email etc. It requires coordination with AoU, FC teams.

**Comment by panentheos** [comment]
This is ready to implement. The header should be `X-App-ID: Saturn`

**Comment by kleighwe** [comment]
Hey y'all! I just checked with Thomas and this ticket (https://precisionmedicineinitiative.atlassian.net/browse/RW-574) is pretty far down the AoU backlog. RE FireCloud, it looks like this is in the next release.

**Comment by zarsky-broad** [comment]
That's no problem, it can be implemented any time after the backend services start supporting it.
