### ISSUE TITLE
Whitelist Prod Saturn users

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#501]
As we start to talk about Saturn to more people, obscurity is no longer an acceptable solution to control early access. Therefore, we should restrict access to the app to an approved whitelist of users.

Brad has a list of usernames who have been approved for access. We should check against this during sign-in. If a user is not on this list, they should see a static page with the following message:

"Saturn is under-development. If you are interested in contributing feedback as part of our user panel, please email saturn-dev@broadinstitute.org" and a signout button

we should handle new user registration appropriately- people shouldn't be presented with the registration screen

**Comment by seanhorgan** [comment]
How is the whitelist maintained?

**Comment by zarsky-broad** [comment]
Manually in code. It's a list of hashed emails. Since we have daily releases, it can be updated daily.

**Comment by dmohs** [comment]
And as-needed if necessary since Circle allows manual triggering.
