### ISSUE TITLE
Add a link or suggestions for Markdown use in MD-enabled areas.

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#522]
In the textboxes that use MD, it may help users to have a link for the syntax or a cheat sheet.

**Comment by bradtaylor** [comment]
Leaving this in new issues for now. Currently Markdown is only on workspace description, and we might be moving away from that

**Comment by bradtaylor** [comment]
We are indeed using markdown

**Comment by bradtaylor** [comment]
Make sure we call out what flavor of markdown we use
