### ISSUE TITLE
For now, only show "My Workspaces" a la FireCloud UI

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#53]

**Comment by bradtaylor** [comment]
Basically, filter such that the only things that appear in saturn are the list that would be in the 'my workspaces' tab in FC

**Comment by zarsky-broad** [comment]
Fixed by #52

**Comment by dmohs** [comment]
I see a different list of "My Workspaces" using the same account on FC dev vs. Saturn dev.

**Comment by zarsky-broad** [comment]
You'll see them sorted differently because fc sorts by namespace/name, whereas we sort by name only. The number of results should be the same.

**Comment by dmohs** [comment]
Now I do see them. I wonder if I had stale code. Rock on!
