### ISSUE TITLE
Spike: Feasibility of IGV desktop

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#544]
Is is feasible to provide a UI for IGV desktop in Saturn? We know that we can spin up a machine with IGV installed similarly to how we provide Jupyter. The question is, can we provide a reasonable UI for this experience? For example, could we run VNC on that machine and provide a connection point to that? Would the experience have acceptable performance?

**Comment by zarsky-broad** [comment]
[NoVNC](https://github.com/novnc/noVNC) hit 1.0.0, and it's available as an npm module...

**Comment by zarsky-broad** [comment]
We could use https://github.com/larryprice/novnc-core or https://github.com/larryprice/react-noVNC (which wraps it)

**Comment by bradtaylor** [comment]
This is on the Leo board for Q1 I believe. @rtitle, do you have any thoughts? Do you either want to take this spike, or punt on it?
