### ISSUE TITLE
Use the new Leonardo endpoint for cluster creation 

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/saturn-ui#548]
I am opening this ticket to let the Saturn team know that a new `PUT /api/cluster/v2/{googleProject}/{clusterName}` Leonardo endpoint, aimed to reduce the cluster creation response time (from ~10s to ~5s) and prevent certain race conditions as explained [here](https://docs.google.com/document/d/10Ljxv5Dcrfj-ozqpd8iAMU6X35LtFekcfHg82Hn-urY/edit) was [released](https://github.com/DataBiosphere/leonardo/releases/tag/RC_Z_2018-08-21) today, and is ready for a spin :) Please let us know if you run into any issues.

**Comment by katevoss** [comment]
@kyuksel Is there anything in particular I should test or be aware of? I changed it to `api/cluster/v2/` and so far it all works as it did before, except faster!
