### ISSUE TITLE
Data Browse: Move from info icons to tooltips

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#554]
The info icon is a bit small and might still be difficult for users to target easily. Instead of requiring the user to target the icon and click, what if we made it display the information on mouseover?

![Screen Shot 2018-08-22 at 9.52.07 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/0fd3ae15-f5b0-4717-848d-96262d7e4c49)

**Comment by dmohs** [comment]
I'd like us to generally avoid mouseover-driven activity, since these also fire when the user's intention is to do nothing more than move the mouse. I think a few pixels of padding would go a long way here.

**Comment by MattPutnam** [comment]
I think designs had us removing these info boxes entirely (and not replacing it with anything)

**Comment by katevoss** [comment]
Note to @bradtaylor: there are a few tooltips on plain text:
<img width="1029" alt="screen shot 2018-09-06 at 10 51 23 am" src="https://user-images.githubusercontent.com/2395211/45165523-0119b080-b1c3-11e8-9ce0-ddecacbe9215.png">

It seems unlikely that a user would see this information except by happenstance that they move their mouse over this part of the text. This is compared to buttons, which users often hover over.
