### ISSUE TITLE
Provide more info than "YYYY" for jobs created in a prior year.

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#568]
The job history page shows only the year for jobs from 2017. Does that mean that on Jan 1, 2019, then a job from Dec 1, 2018 will only show "2018" as the date? Users may want or need more granular information. At a minimum, I think the full date should be shown on mouseover. 

![Screen Shot 2018-08-22 at 10.11.47 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/bc139a5a-3722-4287-8f9f-954e9911b911)

**Comment by bradtaylor** [comment]
We've got hovers for this
