### ISSUE TITLE
Uncaught error when launching analysis that needs data model

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#569]
While testing launching analyses, I tried to launch an analysis by going to **Tools > click on tool > Launch Analysis > [do not select specific data] > click Launch Analysis**.
*Result*: The Launch Analysis button says "Launching Analysis" and it is grey and inactive.

In the dev tools, there was an error in the Network:
```
{statusCode: 400, source: "rawls", causes: [], stackTrace: [],…}
causes:[]
message:"You must set both entityType and entityName to run on an entity, or neither (to run with literal or workspace inputs)."
source:"rawls"
stackTrace:[]
statusCode:400
```
@zarsky-broad for additional details

**Comment by elizzhao** [comment]
intended behavior: launch analysis button should not be active if no data is selected
