### ISSUE TITLE
Add writing guidelines to Style Guide

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#574]
Add writing guidelines to Style Guide for:
- general principles of writing
- error messages
- capitalization (JSON or json)
- verb tense
- addressing audience
- length
- commas (Oxford)
- spacing
- ...and more!

**Comment by zarsky-broad** [comment]
Perhaps this should be a wiki page rather than on the style guide?

**Comment by katevoss** [comment]
Here is the wiki: https://github.com/DataBiosphere/saturn-ui/wiki/Writing-Guidelines

Take a look and comment with your thoughts and items for discussion.

If anyone has more than a handful of quick thoughts and opinions, I can create a Google Doc for collaborating/bickering/convincing.

**Comment by martygardner** [comment]
Well done, Kate! Nice concise guidance. (Not sure if I need commas there ;)  I especially like the "Objective then action" guideline and leading with the most important information. Another rule I would love to standardize on is to omit commas after labels. If the information design is done right, they should not be needed.

Fwiw, Google's [writing guidelines in the Material spec](https://material.io/design/communication/writing.html#principles) are a nice reference that I generally agree with -- with the possible exception of their preference for using numbers in sentences. They might spark other topic ideas.

**Comment by dmohs** [comment]
@katevoss Thanks for doing this and I agree with your guidance.

**Comment by katevoss** [comment]
I added a section for Labels and a link to Material.io. I'll leave this PR open for another day in case anyone has additional requests or suggestions.
