### ISSUE TITLE
Refresh of Data tab doesn't work in a rare case

### ISSUE THREAD

**Issue by melissachang** [DataBiosphere/saturn-ui#580]
This is a corner case, not sure if it's worth fixing.

Repro
- https://test-data-explorer.appspot.com/
- Click button on bottom right, choose workspace, click Import, click on BigQuery_table under Data Model
- In a separate tab, use https://api.firecloud.org/#!/Entities/deleteEntities to delete the entity that was just created
- Refresh first tab. Something will appear briefly, then the screen goes blank

**Comment by bradtaylor** [comment]
Having a React error boundary will help create a better error state than a blank page.

**Comment by bradtaylor** [comment]
We wont do anything specific for this ticket. Situation will be improved by #622
