### ISSUE TITLE
Propose a solution for ensuring a security risk assessment for all changes

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#583]
Requirements:
1. A security risk assessment occurs for each change.
2. Any high-impact changes get a review from Albano.
3. We can show evidence that this happens.

**Comment by dmohs** [comment]
Note: All of Us adds an item to the title of their PRs. For example, "[risk=none]"

**Comment by bradtaylor** [comment]
Proposed solution:
Add a label to every issue indicating low/high risk. SDLC documents that any high risk PR is reviewed by Albano.

General agreement reached in meeting on 9/4. Closing this issue, as it is now SDLC
