### ISSUE TITLE
In Data tab, allow copying of long strings that end in ellipsis

### ISSUE THREAD

**Issue by melissachang** [DataBiosphere/saturn-ui#585]
With the new Data Explorer Export to Saturn feature, there are cohort entities with very long SQL strings:

![query](https://user-images.githubusercontent.com/10929390/44821333-e1263380-aba9-11e8-8fa3-9c4ec4e351cf.png)

I'm not able to copy the SQL query. As a workaround, I've been using "Copy to clipboard".

[This page](http://mattsnider.com/css-string-truncation-with-ellipsis/) talks about how to make a long string that ends in ellipsis, copyable.

cc @malathi13

**Comment by panentheos** [comment]
@melissachang You should be able to copy the whole string by dragging the highlight past the end of the ellipsis. Alternatively, you can triple-click inside the text to select the whole cell.

**Comment by melissachang** [comment]
Thanks, both of those worked. I thought I tried them earlier, I must not have.
