### ISSUE TITLE
Clicking into a cell to edit a tool input scrolls the input, but only the first time

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#592]
https://bvdp-saturn-dev.appspot.com/#workspaces/broad-dsde-dev/jimmy/tools/alex_methods/MutationCalling_QC_v1-1_BETA

Click on an input that has more text than can be contained within the text box. It scrolls. Click again and it does not, so you don't lose your cursor the second time.

**Comment by panentheos** [comment]
I looked into this briefly. It seems to be a quirk of `Interactive` elements that are inputs. It happens on all our styled text boxes, but doesn't happen on browser default text boxes.

**Comment by MattPutnam** [comment]
Confirmed that there's no reasonable way to do this.

**Comment by dmohs** [comment]
So the choice becomes, (a) keep `Interactive` with this bug or, (b) ? @bradtaylor thoughts?

**Comment by panentheos** [comment]
Other options I can see are b) try to track down the bug in Interactive and file a PR. Time/feasibility unknown on this one. c) Stop using Interactive (at least for inputs). Would require us to style with CSS.
