### ISSUE TITLE
TBD- if you are in an open notebook, and you 'apply' a new runtime, what happens?

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#602]
Probably nothing good!

**Comment by elizzhao** [comment]
When I tried this, an error banner did not pop up, but it 
a) wouldn't run the notebook lines of code
b) autosave fails, when trying to manually save we get this message:
<img width="627" alt="screen shot 2018-09-05 at 3 26 57 pm" src="https://user-images.githubusercontent.com/42386483/45116265-2acdcb80-b120-11e8-868f-e1327021bbe6.png">
