### ISSUE TITLE
Error when launching analysis without data model but with parameters using "this."

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#604]
There is a icon next to the parameter that is using "this." that says "Expressions beginning with "this." are only allowed when running with workspace data model. However workspace attributes can be used". 

<img width="869" alt="screen shot 2018-09-04 at 3 22 19 pm" src="https://user-images.githubusercontent.com/2395211/45053100-f215ef80-b056-11e8-916a-c9aab2185fd0.png">

But I can still click the button to **Launch Analysis**, and when I do the Launching modal hangs and no analysis has been launched:

<img width="1233" alt="screen shot 2018-09-04 at 3 09 17 pm" src="https://user-images.githubusercontent.com/2395211/45052444-d1e53100-b054-11e8-878e-d2ac1f3e0d84.png">

_Desired behavior:_ 
When a data model is not selected and there are parameters defined with "this.", the Launch Analysis button is greyed out, and the same error message ("Expressions beginning with "this."...) is displayed, so the user knows what to change.

**Comment by MattPutnam** [comment]
Fixed by #610
