### ISSUE TITLE
Switch from accepting signed URL to GS URL in data explorer import

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#606]
Currently BVDP data explorers such as Nurses and AMP-PD are sending json files for import into Saturn via signed URL. This has been deemed unacceptable as it is possible that any 3rd parties who obtained these URLs and access this content

A suggestion from the DE team is to instead provide a gs path to the json file. Our system service account would be given permissions to read it. Permissions would otherwise be restricted.

**Comment by dmohs** [comment]
Signed URLs are temporary passwords. Third parties who obtain passwords may access content. We make efforts to not disclose passwords to third parties. The alternative, eliminating password use, is not a feasible solution.

**Comment by bradtaylor** [comment]
@kleighwe Can you organize a conversation around this topic with Melissa from Verily? It should include @panentheos and @dmohs, possibly @zarsky-broad given the work with signed URLs from Martha

**Comment by kleighwe** [comment]
@bradtaylor scheduled something for next week! :)

**Comment by bradtaylor** [comment]
Not doing this for now. Fine with signed URLs for the moment. Moving this out into the future provides us more flexibility once entity service arrives, etc. There exist a number of options. Closing this until P&S requires it

**Comment by melissachang** [comment]
FYI -- Andrea said the new EntityService will eventually accept GCS file as input. So Data Explorer could give the user proxy group or pet SA read access to the entity file.
