### ISSUE TITLE
Creating and updating cluster doesn't give user enough feedback

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#613]
While updating the runtime specs of a cluster, I clicked to open a notebook. The opening page stuck around for so long that I thought it had failed, but a few minutes later the notebook opened. I think that we should give more feedback to the user (animations, etc) to let them know that their notebook is actually opening.

<img width="1240" alt="screen shot 2018-09-06 at 11 32 05 am" src="https://user-images.githubusercontent.com/2395211/45168115-8ce20b80-b1c8-11e8-9f8f-9f9a0e4ed1b8.png">

**Comment by katevoss** [comment]
No longer an issue now that #589 makes the notebook load much faster

**Comment by katevoss** [comment]
I think this is still a problem when a user is trying to open a notebook and they are waiting 5+ minutes for their cluster to start. The user does not know that the cluster is still starting, and it looks like the page has frozen. I think that some kind of animation would be helpful in telling the user that the app has not crashed and that they just need to wait a little longer. 
Illumina example:
![belatedportlychuckwalla-max-1mb](https://user-images.githubusercontent.com/2395211/46481375-4381dd80-c7c1-11e8-8a6c-21a3a0324c82.gif)

**Comment by bradtaylor** [comment]
Can we distinguish runtime creation from runtime start, and include an explicit message:
1) that this can take 5-7 minutes
2) that the user can nav away and come back once their runtime is in status 'running'

Is the spinner sufficiently animated to convey "we're not dead here"
