### ISSUE TITLE
Implement design update on several pages

### ISSUE THREAD

**Issue by MattPutnam** [DataBiosphere/saturn-ui#616]
Workspace list: https://projects.invisionapp.com/d/main#/console/13746874/286545627/preview

Groups list: https://projects.invisionapp.com/d/main#/console/13746874/307724355/preview

Group edit: https://projects.invisionapp.com/d/main#/console/13746874/307724358/preview

Note the fadey half border thing. This was implemented for the Browse Data page. Also the card/list view buttons on the workspace list.

The fadey half border is also in the designs for the Dashboard and Notebooks tabs, but those pages are still in flux anyway, so don't bother for now.

**Comment by katevoss** [comment]
Another item missing from the Workspaces list: there is a 3-dot menu on the list view:
![screen shot 2018-09-10 at 2 01 06 pm](https://user-images.githubusercontent.com/2395211/45315301-04ce6f80-b502-11e8-9734-725086ac30a3.png)

which should be a menu: https://projects.invisionapp.com/d/main#/console/13746874/311433498/preview

If this is out of the scope of this ticket I can create a new one.

**Comment by elizzhao** [comment]
I can probably add it in this design update!

**Comment by elizzhao** [comment]
^^apologies for all the connecting and moving--was trying to organize so all the relevant branches were attached and in the right place

**Comment by elizzhao** [comment]
three dots menu aspect moved to a new ticket: #642
