### ISSUE TITLE
Clusters can be deleted by another user on same billing project

### ISSUE THREAD

**Issue by elizzhao** [DataBiosphere/saturn-ui#617]
The case where two people are working on the same billing project, one person applies a new cluster (thus deleting the old), however the other discards (thus deleting the new), both people will lose all their clusters! 

Case where one person is working on a notebook and someone else changes the cluster of their joint billing project, the person working on the notebook will have had their cluster removed perhaps without their knowledge. NOTE: hopefully this case is fixed by #602, we should test once those changes are made. 

@bradtaylor @martygardner  for ideal user experience input

**Comment by bradtaylor** [comment]
Can this really happen? I thought we create a cluster per user per billing project. Clusters have the default service account set to the user SA for example

**Comment by bradtaylor** [comment]
We should not be intending to support shared logins. Shared logins are highly discouraged.

**Comment by panentheos** [comment]
This can only happen with two logins of the same user. Closing with no action, since this isn't a supported case.
