### ISSUE TITLE
Make view style persist between page changes

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#625]
As a user, I click to view all Workspaces as a list. Then I click into a workspace, then back to the list of workspaces, and all of the workspaces are now displayed as Cards. When the user selects a card or list view for a page, it should persist for a while.

**Comment by bradtaylor** [comment]
Should apply to each list individually (ie selecting list on workspaces should not apply it to tools!)

Should apply while user is in same session, unless they sign out or close the tab or something.
