### ISSUE TITLE
Add full date on hover to workspace list, in list form

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#626]
I forgot that Workspaces can be both short cards and long cards (list and card style). This PR will add the full date on hover for when the Workspace is a long card. 

@lstrano-broad @panentheos @bradtaylor Right now the hover shows up far to the right of the actual date. I moved the date to make this match, thoughts?

before: 
![Screen Shot 2018-09-10 at 4.26.11 PM.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/aaf9f581-753d-4153-8c5f-32840c1adf3f)

after: 
![Screen Shot 2018-09-10 at 4.46.47 PM.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/ee2836ad-5efe-4468-b25c-3cf2a9281a31)

**Comment by lstrano-broad** [comment]
Thx Kate, check the Invision mock. Date is should appear above collaborators. 

Let me know if you have questions.
Thx
Lou

**Comment by katevoss** [comment]
@lstrano-broad Thanks for pointing out the date location, here is an updated screenshot:

<img width="1166" alt="screen shot 2018-09-11 at 10 45 23 am" src="https://user-images.githubusercontent.com/2395211/45367694-d73fff80-b5af-11e8-9313-d775607135f8.png"> 

I've noted in #628 that the Create a New Workspace card should be a card even in list view, and in #629 to add the 3-dot menu, so those will be fixed separately.

**Comment by lstrano-broad** [comment]
Great thx - date looks good.
