### ISSUE TITLE
Unable to run a workflow that has outputs

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/saturn-ui#630]
I'm trying to run the [TopMed_Variant_Caller](https://github.com/DataBiosphere/topmed-workflows/TopMed_Variant_Caller), which I imported from Dockstore.

I can run it through FireCloud in this same workspace.

In Saturn I am prevented from running it because there are output fields and it indicates that they are required. It is unclear what I am supposed to set this to. My intent was just to run the workflow and dig the outputs out of the cromwell workspace.

The variable in question is:

    TopMedVariantCaller  topmed_variant_caller_output File

I tried to set this to a `gs://` path but get:

Error 403: Attribute namespace validation failed: [Invalid attribute namespace gs]
Source: rawls

I think that the output fields should not be required.

**Comment by dmohs** [comment]
I'm not sure where the mismatch is here, but I believe all outputs are actually optional. We're potentially over-validating.

**Comment by mbookman** [comment]
Any chance this could be fixed before Tuesday? I am giving a demo and it would be great to not need to drop over to FireCloud to launch the workflow.

Thanks!

**Comment by pgrosu** [comment]
@mbookman That's just a local file that gets compressed, like this so just give any simple name without spaces (the ... just stands for longer text that is part of the workflow):

```
    # Tar up the output directories into the output file provided in the input JSON
      tar -zcvf topmed_variant_caller_output.tar.gz /root/...

    }
...
 output {
      File topmed_variant_caller_output = variantCalling.topmed_variant_caller_output_file
  }
```

**Comment by bradtaylor** [comment]
@mbookman In this case you can append the file to workspace global variables. So input workspace.variant_output and it will show up as a new global variable.

Putting in a literal like ""topmed_variant_caller_output.tar.gz" doesn't validate. It explicitly want's "this" or "workspace". If you aren't using the workspace entity model as your input then the output should not be marked as required and you should be able to leave it blank as Matt is requesting.

**Comment by mbookman** [comment]
That worked. Thanks Brad!
