### ISSUE TITLE
Show the authorization domain in the workspace summary

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#631]
Currently there is no way to know what auth domain a workspace belongs to. This may be one or more groups like fake@firecloud.org, superfake@firecloud.org, etc. Usually one group, but this is not limited. In practice, the most you see is two or three.

**Comment by lstrano-broad** [comment]
![Screen Shot 2018-10-05 at 9.47.27 AM.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/465721b4-b2dd-4ac4-8a2e-0a1a64514875)

Let me know if the header should read something else...

**Comment by katevoss** [comment]
Should the header be "Authorization Domains"? For consistency's sake

**Comment by lstrano-broad** [comment]
Yeah, agree with you but would love to somehow connect this header with the concept of Groups and the Groups creation page. May that page needs an updated name to include domains????

**Comment by bradtaylor** [comment]
It should be Authorization Domain singular. It's one domain comprised of several groups. We can change the name there but it would need to go through compliance. Not something we want to take on right now.

I think a little explanatory text could be helpful:
"Collaborators must be a member of all of these [groups](https://bvdp-saturn-prod.appspot.com/#groups) to access this workspace." with the groups link included

**Comment by lstrano-broad** [comment]
Sure - screen updated....
![Screen Shot 2018-10-09 at 2.32.00 PM.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/672eee55-b746-401a-9dd4-5e18e458fb95)
