### ISSUE TITLE
SPIKE: Can we put an 'are you sure' when navigating 'back' from the notebook

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#633]
On a mack laptop I often accidentally make the 'back' gesture when attempting to scroll up. This is very annoying from within my notebook! If I have a cell that takes several minutes to run, that progress is lost. Could we put an 'are you sure?' popup there?

**Comment by panentheos** [comment]
Sort of. We can intercept all page transitions while you're in a notebook, but I don't know if we can differentiate the kind of navigation, e.g. back button vs clicking a link.

**Comment by bradtaylor** [comment]
I'm happy to confirm even if it's a forward nav. Any nav except hitting the 'x' to close button

**Comment by bradtaylor** [comment]
Investigate/prototype

**Comment by bradtaylor** [comment]
duplicate of #470
