### ISSUE TITLE
Add tool description to tool detail

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#646]
In the list of tools, there is no description nor is there a description when a user is viewing a specific tool. Users can put a description in their FireCloud method but currently it doesn't show up in Saturn in the list of tools.

After some investigation, I believe that the description (or 'synopsis' in FireCloud parlance) comes from calling GET https://api.firecloud.org/api/methods/definitions.

**Comment by bradtaylor** [comment]
We should display both 'synopsis' and 'description' on the tool details page. Not on the list.

**Comment by bradtaylor** [comment]
See mockup here with description given a small area that can be expanded/collapsed
https://projects.invisionapp.com/d/main#/console/13746874/318884185/preview
