### ISSUE TITLE
Preserve some state on back/forward navigation

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#65]
For example, when I use the browser's back button to return to the workspaces list, my page position should be preserved. This generally means we need to save some of the page state.

There are two obvious place to encode state: The URL and the `state` object in `window.history`. The choice depends mainly on whether the state should persist beyond the current user's session. As a rule of thumb, if the recipient of a URL via email should have the state in question, and it is not part of the API response that is normally parsed by that page, then it likely belongs in the URL. Window history state is a good place for caching an API response, for example, to ensure the UI feels responsive during navigation.

From https://developer.mozilla.org/en-US/docs/Web/API/History_API:
> we impose a size limit of 640k characters on the serialized representation of a state object. If you pass a state object whose serialized representation is larger than this to pushState(), the method will throw an exception.

**Comment by dmohs** [comment]
Isaac brought up a couple of other options here. One solves the particular example I mentioned above: Render workspace details as a child of the workspaces list so the state is preserved because the component that owns it is still on the page. That will not preserve state, however, when you navigate to a different part of the application.

Another option is to store state in something like Redux so it's global. However, there is no reason that the workspaces list shouldn't appear in your history multiple times, so we'd still have to come up with a way to store distinct copies for different moments in time.

I still believe utilizing the state object in window.history is the right choice here. My understanding is that it even preserves state in cases like duplicating a tab or restoring a window. In other words, it preserves state in cases where the user might expect it. @zarsky-broad thoughts?

**Comment by zarsky-broad** [comment]
I agree. `History.state` is the way to go.

**Comment by MattPutnam** [comment]
What's the scope of this ticket?

Also, I'm not sure how I feel about pages being in different states depending on if you nav back via the back button or via clicking nav controls. That is:

* Start on page A
* Do something that should be saved
* Click to nav to page B
* Go back to page A via some nav control
* State is not restored
* Click browser back button twice
* State is restored

**Comment by dmohs** [comment]
@MattPutnam Great point. I think this behavior can be controversial, so my judgement is that the exact scenario you describe above is the correct behavior until usability testing proves otherwise. Can we agree that this is an acceptable place to start?

**Comment by bradtaylor** [comment]
I'm highly in favor of preserving pagination state of a list on 'back'. I'm ok with that resetting if I navigate 'forward' to that page via nav controls.

I agree with this behavior until usability testing indicates a difficulty.

Can this issue proceed?

**Comment by kleighwe** [comment]
Fixed by Redux!

**Comment by dmohs** [comment]
Let's wait until this is actually fixed before closing it. Redux may be the solution, though I'm skeptical as noted above.
