### ISSUE TITLE
Handle markdown in workspace cards

### ISSUE THREAD

**Issue by panentheos** [DataBiosphere/saturn-ui#656]
Workspace descriptions can use markdown, but we don't process them when displaying the description on the card views. We should handle it somehow.

We could easily render the markdown for the short card, but the long card only has one line, which would result in titles getting chopped.

![image](https://user-images.githubusercontent.com/555632/45629834-4e204100-ba65-11e8-9d7a-f684e13c4fb2.png)

**Comment by bradtaylor** [comment]
Keep the line breaks.
Do not render the markdown.
Ideal would be to strip the markdown.
