### ISSUE TITLE
Tool input json upload not respecting quotes

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#660]
When uploading an inputs JSON downloaded from Dockstore, string inputs that are quoted in the original inputs json are not quoted in the text boxes for tool inputs. This causes them to fail validation. Manually adding quotes causes validation to pass. See below. The top input I manually fixed, the bottom input is the original form.

![Screen Shot 2018-09-17 at 12.41.57 PM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/82a93d74-e177-43e7-9800-1e3aadb10600)

**Comment by mbookman** [comment]
+1

I ran into this today as well. Worked around by breaking up my inputs.json and importing in FireCloud.

**Comment by bradtaylor** [comment]
Example dockstore workflow, with inputs JSON:
https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/TopMed_Variant_Caller:1.17.0?tab=files

**Comment by elizzhao** [comment]
Aiming for: inputs that are references (beginning with this. or workspace.) should be populated without quotes, everything else should populate with the quotes. This is based on the FireCloud model for how they parse JSON
