### ISSUE TITLE
Design a new logo

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#665]
When the new name for Saturn is released, design a new logo to represent the application.

**Comment by bradtaylor** [comment]
New name secured. Issue unblocked

**Comment by lstrano-broad** [comment]
We're getting close, here are the two favorites so far....

![Screen Shot 2018-11-20 at 9.04.56 AM.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/d4e00d07-394a-47d2-8db5-99be59c728c0)

![Screen Shot 2018-11-20 at 9.05.36 AM.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/241286cb-7bc8-44cf-a48b-042e4bd6360a)

**Comment by lstrano-broad** [comment]
Final logo design to be announced at some point today....
![Screen Shot 2018-12-03 at 9.56.59 AM.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/fceeaa0a-1ab1-47af-9dc0-89b243c49afe)
