### ISSUE TITLE
Change the domain at which Saturn is deployed.

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#667]
Currently Saturn is deployed at appspot.com. When the new name is released, choose a permanent domain at which to deploy the UI and shift deployment to this domain.

Important: When we do this, we must also implement a full redirect from the old domain, so that data and tool import links continue to work (they will take some time to migrate). All url params must be forwarded.

**Comment by bradtaylor** [comment]
We have an application name. Can choose a domain

**Comment by katevoss** [comment]
@zarsky-broad suggests https://terra.bio. Or we can hustle terra.io from the current owner.

**Comment by kleighwe** [comment]
Waiting for confirmed domain names

**Comment by bradtaylor** [comment]
See Brad for confirmed domain name. We're ready to move here

**Comment by bradtaylor** [comment]
Step1 configure DNS on domain
