### ISSUE TITLE
Granting "Reader" privileges on a workspace yields 404 on workspace access

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/saturn-ui#675]
I shared another user as a Reader.

When he open the workspace, he gets:

    Error loading workspace: <project>/<workspace> does not exist

which we could see in the Chrome Developer Tools was due to a 404 on reading the bucket.

When I changes his permissions to Writer, he is able to access the workspace just fine.

**Comment by mbookman** [comment]
Thanks @MattPutnam.
The problem also no longer reproduces for me.
I tested with a new workspace. Hopefully this is actually fixed, rather than some other subtlety in the what was in that workspace or how it was shared.
Do you know where in the code the bucket grants are issued on sharing? I'd be interested to see if anything changed recently.

**Comment by MattPutnam** [comment]
Somewhere deep within Rawls. I can't imagine this had anything to do with our code, or anything to do with how it was shared.
