### ISSUE TITLE
Spike: AoU Cohort Builder as a module

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#679]
It the long term, we may decide that the most efficient use of our engineering resources involves using the same code base for Saturn and All of Us with only branding and small feature differences. To help understand the amount of work necessary to accomplish this, I'd like to investigate what it would take to incorporate the cohort builder without re-writing it. Can we try to make it into a module and place it somewhere on the Saturn UI?

**Comment by bradtaylor** [comment]
Not Doing, per @dmohs
