### ISSUE TITLE
SPIKE: Read only notebooks for workspace READERS

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#705]
We would like to provide workspace readers a way to view the content of notebooks without being able to edit cells or run the code. Not having this is hurting our users since they have to give people edit permissions to their code resources just to read them!

Desired UX:
1) workspace WRITERs click on a notebook card and it opens in jupyter as per normal
2) workspace READER clicks on a notebook card:
* Content appears framed into the main workspace app as it usually does with Jupyter, with the close button and everything
* Instead of an editable, runnable notebook, users see a static read-only view of both code and outputs.
* We add a notice up at the top of the page "Viewing this notebook in read only mode, Copy to another workspace to edit and run". This presents as a link or button for copying the notebook to another workspace per #722 
* The copy-to-another-workspace affordance on the notebook card allows the user to copy the notebook to another workspace where they have writer, where the subsequent behavior is (1) from above.
* The URL at the top of the page is the same when viewing a notebook in either (1) edit or (2) read only mode. If a workspace READER copied that link and passed it to someone who was a workspace WRITER, their experience would be (1)

How can we accomplish this?

Jupyter allows for notebooks to be saved as html, markdown or pdf in addition to ipynb. Might this facility be useful?
Jupyter can convert notebooks between formats via the command line as well- not just via the jupyter UI.
https://github.com/jupyter/nbconvert

We'll start with a doc and go from there. Likely that HTML is the best option? :)

**Comment by bradtaylor** [comment]
nbviewer appears to be a server, rather than a js module: nbconvert as a service

We could run a lightweight server, call this, get the HTML back, and place it in our app?

**Comment by bradtaylor** [comment]
From what I've seen so far, it seems like nbviewer would be fast enough that we could set up our own server for this, and whenever a READER clicks the notebook card we send the ipynb to the nbviewer server, get back HTML, and plug that into our page.

This is attractive because we only have to store the original ipynb. That makes things like cloning and copying to another workspace much easier and keeps storage costs down.

**Comment by bradtaylor** [comment]
@elizzhao Had some more discussion among the PMs on the desired behavior here. I've updated the issue description above to capture that

**Comment by elizzhao** [comment]
Ticket #748 created as the result of this spike. Closing this issue since we've decided how we wish to accomplish it.

**Comment by calbach** [comment]
@bradtaylor whose server is this? Could this be part of Leo so that AoU can reuse this work?

**Comment by dmohs** [comment]
That's a great point. This does seem like a generally-useful notebooks feature.
