### ISSUE TITLE
Design polishes part B

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#709]
- [x] Workspace card, menu few pixels smaller and badge slightly bigger than menu
- [x] Update terminal icon from mock, get svg from Lou
- [x] 'Built on' sizing and color
- [x] Autofocus needs blue outline when active, first active
- [x] Vertically align the workspace title and description in list view
- [x] When cloning workspace, move info about inherited auth domains below Auth Domain, move info about Auth Domain inheritance below drop down - Show to Lou
- [x] Workspace clone button in menu, update icon to menu
- [x] Menu in workspace summary have same three dots but in white

**Comment by elizzhao** [comment]
Also added design updates to left nav bar (fixed margins, font weights, and naming to match invision)

**Comment by elizzhao** [comment]
Edit: removed adding terminal access to left side menu after consultation with Brad
