### ISSUE TITLE
Breadcrumb to Home missing

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#714]
In @lstrano-broad's designs there is a Breadcrumb that links to Home, but currently it is not implemented:
<img width="1003" alt="screen shot 2018-09-28 at 11 14 05 am" src="https://user-images.githubusercontent.com/2395211/46217301-9b2acf80-c30f-11e8-84e6-7fb1a868ba87.png">

Is this an intentional omission, or is it something we plan to implement? If the former, feel free to close this ticket. If the latter, this ticket is to add the Home breadcrumb.

**Comment by lstrano-broad** [comment]
Good catch. No need to have Home. We'll start the breadcrumb with Workspaces. I'll update the screens in Invision to reflect this.
