### ISSUE TITLE
Better experience when a user attempts to access a workspace without permission

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#718]
Currently, if a user attempts to access a workspace which does not exist, we display an infinite spinner. Currently if a user attempts to access a workspace to which they are disallowed, we display the following:
![Screen Shot 2018-10-01 at 12.01.57 PM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/fbcea2fc-4176-41fb-8b31-0e6784d268ab)

In both cases, we should display the same message. The text of the message should be updated to include information on authorization domains. Copy:

> ## Could not display workspace.
> 
> Either the requested workspace does not exist, or you do not have access. To view a workspace, the owner must share it with you, or with a Saturn group(link to the groups page) you are a member of. In addition, if the workspace is protected under an [Authorization Domain](https://software.broadinstitute.org/firecloud/documentation/article?id=9524), you must be a member of every Saturn group composing this Authorization Domain.
> 
> If you suspect you do not have access, please contact the workspace owner.

**Comment by kleighwe** [comment]
@katevoss will quibble with the wording.

**Comment by katevoss** [comment]
> ## Could not display workspace
> 
> You are trying to access a workspace that either does not exist, or you do not have access to it. If you suspect you do not have access, please contact the workspace owner.
> To view an existing workspace, the owner must share it with you or with a [group](https://software.broadinstitute.org/firecloud/documentation/article?id=9553) of which you are a member. 
>If the workspace is protected under an [Authorization Domain](https://software.broadinstitute.org/firecloud/documentation/article?id=9524), you must be a member of every group within the Authorization Domain.
