### ISSUE TITLE
Illegal characters in Notebook names

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/saturn-ui#72]
Some characters (`?` is known) seem to cause issues when localizing notebooks. Find a way to escape or prevent them.

```sh
gsutil -m -q cp -R -c -e 'gs://fc-bebc25c4-0f95-44b1-94ff-0dfcc63a8e93/notebooks/last time?.ipynb' '/home/jupyter-user/jimmy/last time?.ipynb'
CommandException: Destination (/home/jupyter-user/jimmy/last time?.ipynb) must match exactly 1 URL
```

(from #33)

**Comment by kleighwe** [comment]
@dmohs will ask @rtitle if this is something that the Leo team has on their horizon.

**Comment by dmohs** [comment]
Slacked Rob today.

**Comment by rtitle** [comment]
It wasn’t — gsutil discourages using these characters in object names: https://cloud.google.com/storage/docs/naming#objectnames

I suppose we could look into whether it’s possible to escape them in the gsutil command, or strip them out somehow.

**Comment by bradtaylor** [comment]
I'm ok adhering to object name conventions here (they allow spaces!), so long as we warn users appropriately and tell them what to change.
