### ISSUE TITLE
Add an "Analysis Library" section to the application

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#720]
We wish to provide users with a library of useful analyses to jumpstart their science. These help users understand the system and provide tools they can borrow and run on their own. This will range from smaller examples of a single analytical tool (like calling structural variants) to full reproductions of a paper. These will be expressed as full workspaces with WDLs, notebooks, and example data. To start, we will use the 9 featured workspaces created by the GATK group.

Add an "Analysis Library" section to to the left-hand nav. This should link to a list of featured workspaces. There should be a brief instruction to the user:
"Browse example workspaces demonstrating useful analyses. Clone a workspace to re-run the analyses for yourself, or export individual data and tools to your workspace of choice."

This should be followed by the list of 9 featured workspaces. These can be identified as they are in FireCloud. For each, we should show the same information as on typical workspace cards (name, the last modified date, and the first line of the description (with any markdown stripped). Option to clone (users will not be able to share and delete these).

It would be nice if we could do something visually more stylish, similar to the data library. We may add the general ability to associate an image with each workspace for use in the cards. Can we, for now, just special case these 9 and add an image?

Once the main list is in place, we should also add a third option to the "Explore tools" navigation, after dockstore and FC methods repo, linking to the analysis library. This should carry the same instruction as above:

> ## Browse pre-built analysis workspaces
> "Browse example workspaces demonstrating useful analyses. Clone a workspace to re-run the analyses for yourself, or export individual data and tools to your workspace of choice. The Analysis Library can also be accessed from the main navigation panel"

**Comment by bradtaylor** [comment]
Lou was disinclined toward adding this as a third option beneath "Explore tools", since it's already a top-level nav feature. I'm happy to follow design's lead here.

**Comment by lstrano-broad** [comment]
Updated screens and updated left hand nav in Invision
