### ISSUE TITLE
On WDL workflows, add a "Copy to another workspace" option

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#721]
We want to give users the ability to send interesting WDL workflows from example workspaces like those in the Analysis Library to their own destination workspace.

Users should have this option from the tools card/list view, or from the tool details page. This functionality was available in FireCloud, where it was implmented as a pull. I'm suggesting we change that to a push, since we expect one of the main paths to be from the analysis library. We'll have other affordances in the workspace for to guide users to go find code.

Selecting the "Copy..." should allow users to select an existing workspace, or create a new one using the standard modal.

**Comment by kleighwe** [comment]
Whoever picks up this ticket, check with @lstrano-broad regarding design.
