### ISSUE TITLE
On Notebooks, add a "Copy to another workspace" option

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#722]
We want to give users the ability to send interesting notebooks from example workspaces like those in the Analysis Library to their own destination workspace.

Users should have this option from the tools card/list view, or from the tool details page. I'm suggesting this be a push, since we expect one of the main paths to be from the analysis library. We'll have other affordances in the workspace for to guide users to go find code.

Selecting the "Copy..." should allow users to select an existing workspace, or create a new one using the standard modal.

The result of this should be that the notebook file of interest is copied to the destination workspace bucket, creating a second artifact that can subsequently diverge from the source.

**Comment by bradtaylor** [comment]
We want to give users the ability to send interesting notebooks from example workspaces like those in the Analysis Library to their own destination workspace.

Users should have this option from the tools card/list view, or from the tool details page. I'm suggesting this be a push, since we expect one of the main paths to be from the analysis library. We'll have other affordances in the workspace for to guide users to go find code.

Selecting the "Copy..." should allow users to select an existing workspace, or create a new one using the standard modal.

The result of this should be that the notebook file of interest is copied to the destination workspace bucket, creating a second artifact that can subsequently diverge from the source.

**Comment by kleighwe** [comment]
Check with @lstrano-broad before starting RE design.

**Comment by elizzhao** [comment]
If the workspace being copied into already has a notebook of the same name, warn user and give the option to override or to cancel/rename before copying
