### ISSUE TITLE
Add/update data tables from TSV

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#738]
Users need to create new tables in Saturn representing their data. The most common way to do this is by uploading a tabular file exported from a program like Excel.

In the data tab, there should be an "Add Data" affordance. Ultimately, users will be able to add either tables or files here, but for now, we'll just handle the case of tables.

There are two things a user will need to do:
1) Create a new data table
2) Add data to an existing table.

In (1), the user would upload their flat file. Currently, TSV is the only format supported by the backend. (In the future we'll also likely want CSV). The table name (entity type) should default to the name of the file. It would be nice if the user could also optionally specify a different name.

In (2), the user would select an existing table, and upload a flat file. Columns and rows not present in the existing table would be appended. Columns and rows already present in the existing table would be overwritten with the new values from the file.
https://software.broadinstitute.org/firecloud/documentation/article?id=10892

The user MUST be able to specify custom table names (entity types). We will not restrict users to uploading tables corresponding to participants/samples/pairs.

In either case (1) or (2), we place some requirements on the format of the file. We should either inform the user of these requirements, allow them to download a blank template, or link to documentation about format restrictions. (Or all of the above).

For example, we require the first row of the file be the intended column headers. We also need to highlight a primary key column, which contains the unique identifiers for each row. This column cannot contain duplicate values. We require users to call out this column by including "entity:" as a prefix on the column name. We may also require that it end in "_id"? There are also custom formatting semantics for specifying relationships between fields of different tables.
See the 'sample' example here:
https://software.broadinstitute.org/firecloud/documentation/article?id=9771
@ahaessly Is there anything else notable about the file format here?

**Comment by bradtaylor** [comment]
Blocked on backend work to allow TSV upload for custom entity types.

**Comment by ahaessly** [comment]
"entity:" is required when creating entities from the file. if the file is for upserting, then "update:" should be used.

**Comment by bradtaylor** [comment]
We do not need to handle update at the moment (that will follow on).
See 'add data' affordance in wires:
https://docs.google.com/presentation/d/1-JQd63YQZmKLGPSgvSjRXot8OlFmP3r3D2EaEdgYIyE/edit#slide=id.g3382bde459_1_119

Modal needs to say "Create a new table from TSV" and present a file selection. Drag&Drop optional.

If someone uploads a file with an entity that already exists, we warn "Do you want to replace the <Entity> table?" and provide option to rename the new upload.
