### ISSUE TITLE
SPIKE: Zendesk integration

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#740]
We should validate our assumptions about Zendesk integration. Investigate the steps involved in implementing our two desired flows:

1. An "email support" link that allows easy interaction with the Zendesk instance set up by Comms.
2. A way to prompt for 'net promoter score' and store the results.

Output will be an understanding of how easy/possible this is, and maybe some prototype code.

**Comment by katevoss** [comment]
Useful links: 
- [Add web widget, simple](https://support.zendesk.com/hc/en-us/articles/203908456-Using-Web-Widget-to-embed-customer-service-in-your-website)
  - [Add custom fields to widget](https://support.zendesk.com/hc/en-us/articles/203661496)
  - [Web widget out of the box, an overview](https://support.zendesk.com/hc/en-us/articles/115009692388)
- [Web widget API](https://developer.zendesk.com/embeddables/docs/widget/api)
- [Web widget resources](https://support.zendesk.com/hc/en-us/articles/115004744348)
- [NPS overview](https://support.zendesk.com/hc/en-us/articles/203755166-Creating-and-sending-a-Net-Promoter-Score-survey-to-measure-customer-loyalty)
- [NPS API](https://developer.zendesk.com/rest_api/docs/nps-api/introduction)

Screenshot of web widget, out of the box:
<img width="1422" alt="screen shot 2018-10-11 at 2 48 32 pm" src="https://user-images.githubusercontent.com/2395211/46826716-b4e30280-cd64-11e8-958e-194d551c46f6.png">

<img width="1417" alt="screen shot 2018-10-11 at 2 49 51 pm" src="https://user-images.githubusercontent.com/2395211/46826758-d04e0d80-cd64-11e8-9138-3943950cef0b.png">

**Comment by katevoss** [comment]
### An example workflow, using the simple widget
**0. I submitted a "testing" ticket via this form:**
<img width="1382" alt="screen shot 2018-10-11 at 5 32 14 pm" src="https://user-images.githubusercontent.com/2395211/46873228-0c847b00-ce04-11e8-85aa-435b0a7454e6.png">
**1. an email was sent to me (as the user), confirming my request was received:**
<img width="763" alt="screen shot 2018-10-12 at 9 48 11 am" src="https://user-images.githubusercontent.com/2395211/46873149-e9f26200-ce03-11e8-96fa-e9b6bb6afb49.png">
**2. I received an email (as the agent) about the ticket:**
<img width="797" alt="screen shot 2018-10-12 at 9 47 22 am" src="https://user-images.githubusercontent.com/2395211/46873183-f5de2400-ce03-11e8-8fcc-a8d9ca30efad.png">
**3. On the Zendesk dashboard, I saw the issue:**
<img width="1408" alt="screen shot 2018-10-12 at 9 47 43 am" src="https://user-images.githubusercontent.com/2395211/46873211-01314f80-ce04-11e8-8c19-a31534ca37e7.png">

**Comment by katevoss** [comment]
For the MVP of Zendesk rollout our Communications team is focused on Zendesk Support within Saturn, which enables a user to submit a support request into the Zendesk system. It's not clear yet whether the user is expected to contact support via email or to via a web widget on Saturn.

Code snippet of example customizations:
``` javascript
<!-- Start of katetester Zendesk Widget script -->
    <script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=a30d1ea2-f22c-4cb5-89ef-9c5596c73703"> </script>
<!-- End of katetester Zendesk Widget script -->
<script type="text/javascript">
      window.zESettings = {
        webWidget: {
          contactForm: {
            attachments: false
          },
          position: {
            horizontal: 'right',
            vertical: 'bottom'
          },
          color: {
            theme: '#cc853f',
            launcher: '#cc853f',
            launcherText: '#f4f5ff',
            button: '#8A0648',
            resultLists: '#691840',
            header: '#203D9D',
            articleLinks: '#FF4500'
          },
          launcher: {
            label: {
              'en-US': 'Email support',
              '*': 'Help'
            }
          }
        }
      };
</script>
<script type="text/javascript">
      zE( function () {
        var userName = 'fred'; //HelpCenter.user.name;
        var userEmail = 'fred@gmail.com'; //HelpCenter.user.email
        zE.identify({name: userName, email: userEmail});
      });
</script>
```
And the widget looks like: 
<img width="638" alt="screen shot 2018-10-15 at 5 21 15 pm" src="https://user-images.githubusercontent.com/2395211/46979134-c39c2300-d09e-11e8-9ade-d3de568e0ac1.png">

<img width="508" alt="screen shot 2018-10-15 at 5 21 21 pm" src="https://user-images.githubusercontent.com/2395211/46979139-c5fe7d00-d09e-11e8-97a0-e4090f6753f4.png">

**Comment by katevoss** [comment]
In order to keep the widget hidden, add `suppress: true` to the `contactForm: { }` stanza. [Suppress will hide the widget across all webpages.](https://developer.zendesk.com/embeddables/docs/widget/zesettings#suppress)

**Comment by katevoss** [comment]
Summary of findings:
1. An "email support" link that allows easy interaction with the Zendesk instance set up by Comms.
   - It will be easy to implement a web widget on Saturn that will allow users to submit tickets into the Zendesk set up by Comms
   - We can hide the widget until ready for launch.
   - It will be possible and likely easy to add additional functionality like a searchable knowledge base of help articles in the widget, chat with an agent, etc.
2. A way to prompt for 'net promoter score' and store the results.
   - I haven't been able to try adding a NPS survey because I have a trial Zendesk account and you need one that is "Professional" or "Enterprise" level. 
   - However there seems to be adequate documentation that it is relatively straightforward to do: [How to create/customize a Survey](https://support.zendesk.com/hc/en-us/articles/203755166-Creating-and-sending-a-Net-Promoter-Score-survey-to-measure-customer-loyalty), [Analyze the score](https://support.zendesk.com/hc/en-us/articles/203981113), and the [NPS API](https://developer.zendesk.com/rest_api/docs/nps-api/introduction)

**Comment by katevoss** [comment]
I created a branch #772 with the code to add a widget. Closing this spike as complete.
