### ISSUE TITLE
Download metadata only for certain rows

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#764]
If I select particular rows of a data table, download a TSV containing only those rows.

**Comment by bradtaylor** [comment]
Blocked on #404

**Comment by bradtaylor** [comment]
Adding Needs interaction design.
It's not clear how we want to handle a 'select-all, then deselect1, then take action' flow, given that results are paginated.

Gmail has an additional affordance for selecting beyond the first page.

applies to #723 as well

**Comment by bradtaylor** [comment]
See #723 where we handled selection semantics. It's ok if it's slow/unstable on large data today.

Dynamically decide whether you need to pull data into the browser or rely on the backend. Ask @panentheos @zarsky-broad

**Comment by breilly2** [comment]
FC doesn't currently have support for making a TSV for a subset of entities in a workspace. Do we need that feature or are we planning to generate the TSV client-side?

**Comment by panentheos** [comment]
The plan for now is to generate it client side, but it would be better if the server did it, because the client-side approach has performance issues with large datasets.
