### ISSUE TITLE
SPIKE: Saturn status page

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#767]
Users wish to know whether Saturn or any of it's components are down. What is the Saturn equivalent of status.firecloud.org?

**Comment by elizzhao** [comment]
Firecloud status page uses Pingdom's public status page. Pingdom monitors a website's functionality and the public status page lets users see how the website is currently/has been behaving. Looks like a feature of the Pingdom membership and seems fairly straightforward to set up from their guides.

**Comment by elizzhao** [comment]
Ticket generated as a result of this spike is #791 . Closing this Spike since a path forward has been made.
