### ISSUE TITLE
Link to the FireCloud data library from Saturn Library

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#768]
Users need a way in Saturn to find the following categories of dataset:
1) Datasets sequenced at Broad and delivered through FireCloud / Saturn
2) Public datasets hosted at Broad, such as TCGA, TARGET, etc.

Both of these classes of dataset are hosted FC/Saturn as workspaces, catalogued via a rich dataset metadata schema in the FireCloud data library.
https://portal.firecloud.org/#library

Until such time as these data are discoverable by a dedicated object-level explorer, we will surface them in the Saturn library by adding a new entry:
* Name: FireCloud Dataset Library
* Image: Broad logo
* Participants: XXXX
* Description: "Search for datasets sequenced at the Broad Institute, or public datasets hosted at the Broad. Datasets are pre-loaded as workspaces. You can clone these, or copy data into the workspace of your choice"

**Comment by katevoss** [comment]
To do's:
- [ ] approx. number of participants
- [ ] tooltip for participants
- [ ] tooltip for Browse data button
- [ ] logo size
