### ISSUE TITLE
Adjust the FireCloud methods repository to work from Saturn

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#771]
We are going to be linking users to the FireCloud methods repository to find their pre-existing private mehtods. Per #430 

Ultimately, we're intending to migrate this content to Dockstore, once that system allows private methods. However, linking to FireCloud will serve to expose this content sufficiently early in our beta phase that we can introduce users from FireCloud.

As we are sending users to a different system, we want to:
1) Provide them a way to get back
2) Minimize the disruption

To this end, we intend to modify https://portal.firecloud.org/#methods when a user arrives there from Saturn. How will we know a user is arriving from Saturn? @panentheos has recommended adding a query parameter to the URL to capture this state. The URL therefore specifies when we want to display a Saturn-modified view of this page.

How will we modify the page?
The primary function of the page is to search for WDL workflows, select a version of interest, and export it to the workspace of their choice. For example, a user may select:
https://portal.firecloud.org/#methods/gatk/CNV_Somatic_Panel_Workflow/11
From here they can click "Export to Workspace". This brings up a generic workspace chooser. After the user has chosen a workspace and clicked "Export to workspace", they are shown an "Export Successful" confirmation, with a link to view the workspace in FireCloud. To accomplish aim (1), we want this workspace link to direct to the Saturn version of the workspace. So instead of:
https://portal.firecloud.org/#workspaces/broad-dsde-firecloud-billing/brad_scratch/method-configs/gatk/CNV_Somatic_Panel_Workflow
We want
<saturn-base-url>/#workspaces/broad-dsde-firecloud-billing/brad_scratch/tools/gatk/CNV_Somatic_Panel_Workflow

To accomplish aim (2), we want to remove the page header, which links to many other parts of FireCloud we don't want the user poking at (like the workspace list, data library, profile info, etc). We similarly want to remove the footer (which links to FireCloud TOS, docs, forum, etc).

Ideally, we could replace the header line with a new one containing a link back to <saturn-base-url>, but this is optional.

Things we don't care about:

The visual styling on the FC data library page is widely divergent from the rest of the Saturn app
The URL is under a different domain than the rest of the application.
Ok, we care about those things. But not enough to fix them at this time unless it's dang easy

**Comment by bradtaylor** [comment]
Related to #770

**Comment by katevoss** [comment]
This is complete now that this PR is merged: https://github.com/broadinstitute/firecloud-ui/pull/1440
