### ISSUE TITLE
Add "Beta" ribbon to Saturn

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#778]
Saturn is still in Beta, so let's make it clear to users with a nice ribbon across a corner of the navigation that says "Beta". Then when we release to the general public, we'll remove it.

**Comment by lstrano-broad** [comment]
Example for site-wide header and left hand navigation uploaded to Invision...

https://projects.invisionapp.com/d/main#/console/13746874/332377397/preview

https://projects.invisionapp.com/d/main#/console/13746874/332377398/preview
