### ISSUE TITLE
"Your account is unauthorized" preventing autosave

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#789]
A user reports an issue with their authorization in a noteboook. 
User reports:
"well, bad news.  after working this morning on a nice notebook i suddenly got "your account is unauthorized" at "save and checkpoint". Fortunately i developed some of the code in textedit so i did not lose everything.  Last save and checkpoint succeeded but the careful narrative is lost."

Is this the credentials refresh error we've gotten previously?

**Comment by panentheos** [comment]
This was fixed via google project config settings, closing.
