### ISSUE TITLE
Create a public facing saturn status page

### ISSUE THREAD

**Issue by elizzhao** [DataBiosphere/saturn-ui#791]
This ticket was created out of Spike #767. 
Because saturn uses so many of the same backend services as Firecloud, we would like to start off with a status page that points to the same place as status.firecloud.org. The process for doing so is as follows:
First, speak with @bradtaylor about the domain name for terra/saturn's status page. After we have a domain name, reach out to DevOps about pointing it to the firecloud status page.

**Comment by bradtaylor** [comment]
status.terra.bio

**Comment by bradtaylor** [comment]
If low level of effort, recreate status page with more recent pingdom. If that's hard, point at FC's.

**Comment by panentheos** [comment]
Note: it looks like we can only have one custom domain for that page, which is currently status.firecloud.org, so we may just need to link to that for now. Also, the content of that page doesn't seem very customizable.

**Comment by panentheos** [comment]
Given the above restrictions, we're not going to take any action on this for now. Until we migrate the domain in the future, `status.firecloud.org` will serve as Terra's status page
