### ISSUE TITLE
Health endpoint for Saturn UI

### ISSUE THREAD

**Issue by elizzhao** [DataBiosphere/saturn-ui#792]
Right now our Saturn UI health check just points to: bvdp-saturn-prod.appspot.com/config.json which is not very useful since it just checks whether we can get to that file.

What would be a smarter way to check the health of our app? Firecloud UI has some sort of health check since it's one of the items on status.firecloud.org. What is their health check? Could it be used as inspiration for a better health check for us?

**Comment by panentheos** [comment]
FWIW, Firecloud's health check also just points to a `config.json`, so there's parity there. Barring some sort of fancy solution that downloads and runs the JS, that seems like a reasonable test for "up" for a UI.

**Comment by panentheos** [comment]
I'm inclined to leave this as-is for now. If we decide at some point it's worth pursuing a more specific solution, then we can reopen, but the current approach is straightforward and serves our needs for now.
