### ISSUE TITLE
Users in groups unable to access workspaces!

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#805]
We have had trouble on-boarding multiple users. They are unable to access the workspaces we want to share with them. This occurs when access is granted by the following sequence of events:
1) Workspace is shared with group
2) User is added to group
3) User attempts to access workspace.

They get our typical "404 workspace does not exist or you dont have access" message

This may be because we are changing group membership via Sam API, rather than Rawls. Per @MatthewBemis, "this is a result of our group-update logic being spread across multiple systems. It will be fixed when Phase 4 goes live. Until it goes live, update group membership via the Rawls API. If you are already using the Rawls endpoints, then we'll need to dig in to this bug some more."

**Comment by dvoet** [comment]
this may also be related to authorization domains

**Comment by melissachang** [comment]
So the fix (#808) will be on https://bvdp-saturn-prod.appspot.com/#workspaces Monday around 10am EST?

**Comment by zarsky-broad** [comment]
11am, yeah
