### ISSUE TITLE
Revert to Sam groups management

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#806]
Per #805, we had to change groups management to Rawls APIs. Switch them back to Sam. Blocked on Sam Phase4

**Comment by zarsky-broad** [comment]
Locations in code that need changes are marked with the comment `TODO: Replace when switching back to SAM for groups api`

**Comment by panentheos** [comment]
See git history for previous code when unwinding this, if helpful.

**Comment by bradtaylor** [comment]
Not a straight revert- Brian changed some commented lines
