### ISSUE TITLE
Explain read-only notebook view

### ISSUE THREAD

**Issue by panentheos** [DataBiosphere/saturn-ui#813]
This was split off from #748

When viewing a notebook in read-only mode, we'd like to inform the user about what that means, and offer them the ability to clone the notebook to another workspace (so they can modify it there).

This might require some reorganizing of the page layout to support this.

**Comment by bradtaylor** [comment]
Our design bandwidth is severely constrained. Can we just put some text up in the top-of-page banner (perhaps adjacent to the notebook runtime)?
 "Viewing in read-only mode. To edit this notebook, copy it to another workspace", where copy is a link that brings up the copy-to-another-workspace modal used elsewhere?

@zarsky-broad is this something you can hack? Can we just work off a napkin sketch here?

**Comment by zarsky-broad** [comment]
I'm ok with that
