### ISSUE TITLE
SPIKE: Connecting files from Leo with object storage

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#821]
It's currently difficult to shuttle files back and forth between permanent workspace storage (the GCS bucket) and your Leo vm. You have to shell out to gsutil and manually localize, or use gcsfs or similar libraries.

Can we run a fuse system and mount the bucket as a directory on the Leo VM disk?
There's gcsfuse. Phil Montgomery around here also wrote a kind of fuse system that seems neat, and seems pretty simple to install (Brad can send you an email!)

Different people have different opinions on fuse. We want to learn: How useful and good is this? We need something we can playtest and get a real feel for

Let's make a prototype to play around with and get some feel for how this might work! We can take a couple hours with someone from Callisto and bang on this.

cc @rtitle

**Comment by katevoss** [comment]
Switching back off of this, here are some notes from my investigation:
- [GCS Fuse Google page](https://cloud.google.com/storage/docs/gcs-fuse), [here on Github](https://github.com/GoogleCloudPlatform/gcsfuse)
- [Jupyter FS for GCS](https://github.com/src-d/jgscm) by someone at MIT? 
    -  I haven't yet looked into jgscm
- @MatthewBemis wrote [this doc to discuss approaches for using gcsfuse](https://docs.google.com/document/d/1QD1k2V_48fpIkONMPKe7vA7RGMi7foIG9Y1HHt9yaIw/edit#heading=h.ieo2ojekp6bc) for Rstudio

**Comment by bradtaylor** [comment]
Leo team is prototyping options for Rstudio. I believe this ultimately lies with them, as they pick up added ownership of the full stack UX here. Closing as won't fix
