### ISSUE TITLE
Define Analytics Plan

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#83]
What do we want to learn or control about user success, product health, reliability? What information do we want to capture to answer these questions? How will we be gathering this information technically?

AC:
* A document outlining these questions has been approved by Margaret and Sean.

**Comment by bradtaylor** [comment]
@dmohs I would like you to work with me on this

**Comment by dmohs** [comment]
@bradtaylor I'd say this has enough definition for now. I can attempt to meet our needs with New Relic and then we can iterate.

**Comment by dmohs** [comment]
Reminder that our analytics are here for now: https://insights.newrelic.com/accounts/1862859/dashboards/572556

**Comment by bradtaylor** [comment]
There are some docs on SLIs and KPIs from Kristian.
