### ISSUE TITLE
Remove GCE and GCS scope requests

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#84]
Saturn currently asks for GCE and GCS scopes. Remove these from the scopes we request. Note, we are currently using the GCS scope to list the notebooks residing in a users workspace bucket. We should still be able to perform this list (see implementation note)

Acceptance Criteria:
1) Saturn no longer asks for GCS or GCE scopes
2) All functionality continues to operate, including notebooks file list

Implementation Note: We can get a user's Pet Service Account via a SAM endpoint, and use the SA credential to authorize the bucket ls. The SA has more limited scopes than we ask for from the user. @zarsky-broad has more details

**Comment by bradtaylor** [comment]
Moved this back to in progress as we have to take away https://www.googleapis.com/auth/compute

**Comment by bradtaylor** [comment]
Also remove https://www.googleapis.com/auth/plus.me, which I just learned is not needed

**Comment by zarsky-broad** [comment]
Really, It think we only use email.
