### ISSUE TITLE
Persist Zendesk support modal across pages

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#844]
When a user clicks "Contact Us" in the left hand nav bar, a modal pops up. Users often want to navigate between pages in order to collect information to submit to Support. This modal, that sits on top of the app, would allow a user to switch around to different pages while still having the modal open.

@knoblett @tmm211 @bradtaylor FYI this won't be a part of the V1 launch of the Contact Us button

Related to #735

**Comment by bradtaylor** [comment]
Once Isaac's work for NPS is done, we can likely repurpose that content to suit these needs.

**Comment by kleighwe** [comment]
Refinement Notes:

Do we want to generalize to all modals?
No. This could be too complex for now.
If we build this into the page, the content will persist.
