### ISSUE TITLE
Update error messaging 

### ISSUE THREAD

**Issue by elizzhao** [DataBiosphere/saturn-ui#851]
Change error messaging from a banner that comes down from the top to a toast notification in the upper corner. Also have warning messages here (such as read-only and recently edited notifications from notebooks).

Invision: 
https://projects.invisionapp.com/d/main#/console/13746874/286853469/preview

Characteristics of the notification: 
- doesn't dismiss automatically
- can only be dismissed by clicking the X, rather than the whole area so that the user can click through the messages without closing the whole notification

**Comment by kleighwe** [comment]
Refinement notes: 
- We should figure out if/how we want to show the content. 
- Does Toast support adding buttons to error messages? 
- Note: Think about Z-index issues

**Comment by breilly2** [comment]
Is the intent to attach it to the top-right of the page or the top-right of the window? I think pinning it to the window is better so that it doesn't accidentally go unnoticed.

**Comment by zarsky-broad** [comment]
@breilly2 I believe the intent was the window, yes.

**Comment by breilly2** [comment]
FWIW, the "This notebook has been edited recently" message already looks like the mock-up. I'll take this ticket to mean using the same treatment for other types of messages.
