### ISSUE TITLE
Temporary Workspace Filtering

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#856]
We've onboarded some FireCloud users who have a lot of workspaces (for example, data delivery users). They are going back to FireCloud because we don't provide more filtering on workspaces. 

We want to holistically think through how we're doing search/filter over workspaces. This likely has to wait until Q1. We need a provisional UX solution.

To this end, we need to expose the same filters FireCloud is exposing:
![Screen Shot 2018-11-09 at 1.28.15 PM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/3466fd0d-8bb4-425b-b6c2-5be37aa09dca)

Make an expandable/collapsible panel on the workspace list page exposing these filters. These filters should already have backend support

**Comment by bradtaylor** [comment]
We don't need "TCGA Access"

**Comment by bradtaylor** [comment]
@zarsky-broad has an old mock here that gets us 'round the block

**Comment by zarsky-broad** [comment]
https://www.figma.com/file/L72ELhxEjkgfOhcrhD2d1hFz/Table-refresh?node-id=22%3A58

**Comment by katevoss** [comment]
Two filters:
- [ ] **Access Level** (Writer, Reader, Owner, Project Owner), multi-select
- [ ] **Project** (aka namespace), multi-select

Behavior:
- [ ] only one filter window can be open at a time
- [ ] filter persists when user clicks "Back" button, like card/list view
- [ ] search and filter are additive

**Comment by katevoss** [comment]
@lstrano-broad Do you mind weighing in on the styling of these two filters?

<img width="1431" alt="screen shot 2018-11-20 at 4 45 56 pm" src="https://user-images.githubusercontent.com/2395211/48804923-ef38ab80-ece3-11e8-82ac-5a6da6fffe50.png">
This is the current state, how would you like it to look?

**Comment by katevoss** [comment]
Before someone has filtered workspaces:
<img width="1425" alt="screen shot 2018-11-21 at 2 47 35 pm" src="https://user-images.githubusercontent.com/2395211/48865102-895c2a80-ed9c-11e8-9469-7a495297f388.png">

After filtering workspaces:
<img width="1424" alt="screen shot 2018-11-21 at 2 48 53 pm" src="https://user-images.githubusercontent.com/2395211/48865111-9711b000-ed9c-11e8-8027-a93cf4e8dfe8.png">
I propose that when the dropdown is active, i.e. someone is adding or removing items, that it hovers over the workspaces. When it is inactive then it is collapsed and ends in `...`

**Comment by lstrano-broad** [comment]
Agree that it should - looks better, thx!
