### ISSUE TITLE
Restyle the workflow details page

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#869]
New designs have been produced for the tools detail page. See here:
https://projects.invisionapp.com/d/main#/console/13746874/318884185/preview

Change the existing tools tab to match this styling. Leave the existing 'launch' button in place for now with it's standard behavior. Also ignore "Processing single workflows from files" and the other checkbox. The only thing you can do at the moment is process from a table.

"Select index table" is equivalent to existing "Data Type" selector, and can have the same behavior. "Select index table" is preferable language though.

**Comment by MattPutnam** [comment]
@bradtaylor do you want the Launch Analysis button visible on all of the "tabs", or just on Outputs?
