### ISSUE TITLE
Provide sensible defaults for workflow outputs

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#871]
When workflow output references are written back to a table, users need to enter names for the new columns that are going to be appended.

We can provide sensible defaults for these, and only make the user edit them if they want to. FireCloud already does this with a manual affordance "Populate blank attributes with defaults"
![Screen Shot 2018-11-14 at 4.51.59 PM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/0cd606ad-a1c5-434c-9104-4a48184cec03)

We should use the same defaults but populate them without requiring the user to click anything.

We should show the user where in their bucket actual output files are going to be put (the cromwell submission directory output path). We should let them know references will be written back to the table. We should give users an option to edit the reference column names IFF they want to.

Users should not have to do any actual clicking in order to launch the method. As long as inputs are configured, we've defaulted the outputs and user should be good to go.

See UI mock for outputs configuration here:
https://projects.invisionapp.com/d/main#/console/13746874/326960834/preview

**Comment by katevoss** [comment]
What happens if there is a conflict with items already in the data model and what the sensible defaults are? How does FireCloud handle this?
