### ISSUE TITLE
Contact Us modal should avoid losing user input

### ISSUE THREAD

**Issue by breilly2** [DataBiosphere/saturn-ui#872]
The Contact Us modal is easy to dismiss by either pressing escape or clicking outside the modal. When the modal is re-opened, anything entered is gone. We should put something in place to prevent users from losing what they've typed. Possible solutions are adding a confirmation when closing or not clearing the inputs when toggling the modal's visibility.

Related to #735 and possibly #844

**Comment by kleighwe** [comment]
Refinement Notes:
- Do we want to generalize to all modals? 
 - No. This could be too complex for now. 
- If we build this into the page, the content will persist.

**Comment by kleighwe** [comment]
Once Isaac's work for NPS is done, we can likely repurpose that content to suit these needs.

**Comment by bradtaylor** [comment]
Will not fix- think this may be obviated by #844
