### ISSUE TITLE
No error displayed when uploading a TSV file with duplicates

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/saturn-ui#899]
I tried to upload a TSV file to Terra which inadvertently had a duplicate participant:

```
entity:participant_id<tab>field1
USER1<tab>STUFF
...
USER1<tab>STUFF
```

When uploading to Terra, it appeared that "nothing happened".
I could see in the JavaScript Console there was a 400.

I tested the same file in FireCloud and got the error displayed:

```
Error: Duplicated entities are not allowed in TSV: USER1
Hide Details
Code: 400
Occurred: November 21, 2018, 2:06 PM PST
Source: FireCloud
```

**Comment by bradtaylor** [comment]
Thanks for reporting this @mbookman, we'll get on it!
