### ISSUE TITLE
Workspace Data cannot be defined in Saturn

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#905]
In a new workspace created in Saturn, on the data tab, the Workspace Data is empty with a message saying "No Workspace Data defined". However, there's no way in Saturn to define this data.

If this is a feature coming down the pipeline, then it might be helpful to say that it's coming soon.
If not, then it might be helpful to change the name from "Workspace Data" to something more firecloudy.

![Screen Shot 2018-11-21 at 6.48.01 PM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/6dc09ac4-bb1e-4947-a7bd-ae35f6f2aa70)

**Comment by panentheos** [comment]
This has been fixed by #889
