### ISSUE TITLE
TXT files don't automatically download (like other files)

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#907]
In the data tab -> data table, when downloading a referenced file, if the file is a TXT then the file will not automatically download. Instead, it will open a new tab. Not sure if this is something we can change, but wanted to check.

![Screen Shot 2018-11-21 at 6.55.09 PM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/78924e49-bc08-4b0f-b395-6964315981b9)

**Comment by bradtaylor** [comment]
Unfortunately, it doesn't appear to be something we can easily change. We definitely looked into this
