### ISSUE TITLE
Add a functional React component to All of Us UI

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#909]
All of Us UI code is [here](https://github.com/all-of-us/workbench/tree/master/ui). Select a small component in the UI and render it using React instead of Angular. Some suggestions:
* Create Account page invitation key box
* Report a Bug modal
* A portion of the Create Workspace page
* Some small part of the Workspace Details page

The goal is a small PR with enough infrastructure to enable the migration process.

**Comment by panentheos** [comment]
Result:

https://github.com/all-of-us/workbench/pull/1572
