### ISSUE TITLE
Session time out error when user is signed out and tries to Contact Us

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#912]
Now that we have a homepage and users can view the lefthand nav while signed out, we need to handle the case of signed-out users clicking "Contact Us".
Currently they get an error banner that says "Session Timed Out: You have been signed out due to inactivity" which is not true, the user has not been signed in.

 ![Screen Shot 2018-11-26 at 1.01.55 PM.png](https://images.zenhubusercontent.com/580fc01f95e42b6c5bab0c94/59258df7-640d-4750-93dd-a814266a49eb)

**Option 1:** Users who are not signed in can Contact Us
pros: all users can contact us and we get more feedback
cons: we could receive lots of spam comments

**Option 2:** Users who are not signed in cannot Contact Us
pros: no spam comments and all users are registered
cons: we miss out on feedback from any users who are not signed in

@bradtaylor what do you recommend?

**Comment by bradtaylor** [comment]
Given that we have some pages outside the login boundary, and want feedback, I say we go with Option1 and only protect ourselves if this becomes an issue

**Comment by katevoss** [comment]
Logged-out users will have to fill in their name and email in order to submit the form
