### ISSUE TITLE
Terra Contact button - Attach screenshot ability 

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/saturn-ui#913]
Users using the in-app contact button would like a way to attach screenshots to their question/bug/feature request to make it easier to explain to us what they want.

**Comment by katevoss** [comment]
Docs on Zendesk: https://developer.zendesk.com/rest_api/docs/support/attachments

**Comment by katevoss** [comment]
@knoblett Attachments need to be enabled in Zendesk: 
> To enable attachments from end-users
>1. Click the Admin icon in the sidebar, then select Settings > Tickets.
>2. Next to Attachments, select the Customer can attach files check box.
>3. Click Save tab.

from https://support.zendesk.com/hc/en-us/articles/204265396#topic_c2w_1nx_xdb

**Comment by knoblett** [comment]
This is already enabled; let me know if it does not work from your end.

**Comment by katevoss** [comment]
- Attachments have a [20MB file limit](https://support.zendesk.com/hc/en-us/articles/235860287-What-is-the-maximum-attachment-size-I-can-include-in-ticket-comments-).
- They are already [enabled on Zendesk](https://support.zendesk.com/hc/en-us/articles/204265396#topic_c2w_1nx_xdb).
- For now we'll allow a max of 1 attachment, which users can change after they have uploaded one. 
- Use Dropzone? 
    - should only modal be a dropzone? if the whole page is then it would prevent the user from accidentally uploading a photo/opening it in their browser, which would make them navigate away. So if the whole page is a dropzone then they're not in danger of that.
