### ISSUE TITLE
Circle: Deploy PR on creation

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/saturn-ui#92]
Currently, a PR isn't deployed until there's been a new commit to it, after the PR has been created. The latest commit on a PR should be deployed as soon as the PR exists.

[dmohs] There is a [bug open](https://discuss.circleci.com/t/trigger-new-build-on-pr/4219) to address this. According to [this thread](https://discuss.circleci.com/t/pull-requests-not-triggering-build/1213), Travis supports this.

[dmohs] `git commit --allow-empty` might be a workaround.

**Comment by dmohs** [comment]
Closing because there isn't a good option to do this using Circle's API. Instead, we can rerun the workflow from Circle's UI.
