### ISSUE TITLE
Tool three-dot menu is not opening, instead opens Tool details

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#921]
When I click on the three-dot menu of a specific tool on the #workspaces/<namespace>/<workspace>/tools/ page, it leads me to that Tool's details page. It should open the Tool menu.

@elizzhao may have ideas about what changed recently

**Comment by elizzhao** [comment]
I believe it's because of the change from PR #894 from the toolcard being an href link with Nav.getLink to a function that uses Nav.goToPath
