### ISSUE TITLE
Uncaught rawls errors when attempting workspace clone

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#931]
Sean reported at 9:48:43 on Nov 29 2018 that he was unable to clone, and the application hung. It appears rawls returned 409 (he apparently tried to clone twice to the same name, generating conflict) and we did not handle the error. Possibly the error originated in apache and was HTML instead of JSON, causing us to misshandle it.
![Image from iOS.jpg](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/cd80ecf7-553b-4931-9144-f696353ef146)

When we get 409, we should catch this and tell the user:
*"The workspace [name of clone] already exists. Please chose another name"*

Users are also getting 404 when attempting to clone a workspace. The reason appears to be that they are not on the authorization domain, but are on the workspace ACL. So they see the workspace in their list even though they don't really have access (see #933), and attempt to clone it from the three-dot menu on the card. We should catch this and tell the user:
"You do not appear to have access to [name of original workspace]. It is possible you are not a member of the workspace Authorization Domain. Please contact the workspace owner regarding access to this workspace."
Authorization Domain should be a link to the documentation around AD's.

The route causes of these errors will be addressed elsewhere. For now, we want to appropriately message the error to users and tell them what to do.

**Comment by andy7i** [comment]
FYI - I'm seeing this same issue when trying to create a new workspace with the same name/namespace.
