### ISSUE TITLE
Array attributes should display nested values

### ISSUE THREAD

**Issue by danxmoran** [DataBiosphere/saturn-ui#941]
Currently, array attributes render as `[<size of array>]`:
![screen shot 2018-12-03 at 6 11 22 pm](https://user-images.githubusercontent.com/2755881/49407596-18ffc280-f727-11e8-9f30-e7a1c9cc0d61.png)
I'd expect them to render similarly to the FireCloud UI, which shows the nested values:
![screen shot 2018-12-03 at 6 11 37 pm](https://user-images.githubusercontent.com/2755881/49407624-2ddc5600-f727-11e8-8b09-d8279c96cd2d.png)

**Comment by katevoss** [comment]
Good feedback, thanks @danxmoran !

**Comment by bradtaylor** [comment]
What we would like to do is show a preview of the first few, or a small placeholder message (X items) and the option to click to open up a modal to scroll the whole list

**Comment by elizzhao** [comment]
Implemented as "X items" being clickable to open a modal which allows the user to scroll the whole list
