### ISSUE TITLE
Change config .json file to .env files

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/saturn-ui#943]
`create-react-app` [supports .env files](https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables#adding-development-environment-variables-in-env) for environment specific variables. We should be using those instead of async loading the config.json files.

**Comment by zarsky-broad** [comment]
Mohs brings up the point that this would mean that our builds are no longer environment agnostic, so this is a no go. Instead, we should make sure the config is loaded at early in the app load so if can be referred to synchronously.

**Comment by panentheos** [comment]
Closing this because we're taking a different approach
