### ISSUE TITLE
Linting without IntelliJ

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#95]
I've been uncomfortable tying our linting to IntelliJ. It prescribes an editor when I'd prefer developers are able to choose whatever editor they are comfortable working in.

At the Lead Developer conference, someone recommended [Prettier](https://github.com/prettier/prettier). The suggested approach was to have Prettier auto-commit code fixes to a PR.

**Comment by panentheos** [comment]
I have been thinking this over after some discussions with @zarsky-broad. Breaking things down a bit, here are the decisions at play, from what I see:

### What mechanism we use to perform and enforce the checks.
Given the requirement of editor independence (which I support), I think the most reasonable choice available is ESLint.

### What checks we enforce.
This further breaks down into:
#### Semantic checks
ESLint has a strong set of rules that we can enable to catch likely errors and problematic patterns. This seems like a straightforward choice.
#### Stylistic checks
ESLint has a comprehensive and flexible set of rules we could enable, OR we could use Prettier (which also integrates well with ESLint). Both options seem suitable, so we could take a look at the possible outputs and decide what we want.
