### ISSUE TITLE
update styling of rendered markdown on the workspace dashboard tab

### ISSUE THREAD

**Issue by deflaux** [DataBiosphere/saturn-ui#960]
The dashboard tab in workspaces allows users to have a nice markdown description of the project.

But when we add hyperlinks, e.g. to specific notebooks, the links have the exact same style as unlinked text so we cannot tell that something is a link unless we hover over the text and the browser displays the URL.

**Comment by katevoss** [comment]
Hi @deflaux, thanks for reporting this issue. We are already tracking this problem in #935, feel free to add any details or updates there. Closing this as a duplicate.
