### ISSUE TITLE
Update import tool page with new Terra styling

### ISSUE THREAD

**Issue by lstrano-broad** [DataBiosphere/saturn-ui#967]

**Comment by lstrano-broad** [comment]
new screen uploaded to Invision...
![Screen Shot 2018-12-07 at 3.13.58 PM.png](https://images.zenhubusercontent.com/5ace18884b5806bc2bcea58d/105005be-0130-442e-bfee-e44933c06407)

**Comment by katevoss** [comment]
Currently we don't get the Author's name from Dockstore, neither does FireCloud. Is this something that is important to add? @bradtaylor @lstrano-broad

**Comment by katevoss** [comment]
I created #987 to add the author because currently we don't get that information from Dockstore.
