### ISSUE TITLE
Periodically delete clusters

### ISSUE THREAD

**Issue by dmohs** [DataBiosphere/saturn-ui#97]
CH sent an email about how All of Us Researcher Workbench will periodically delete clusters "to pickup upgrades to the latest Leo cluster version and to upgrade our client libraries." These seems prudent for us to do as well.

Before embarking on an engineering design, we should have a conversations with the Leo team to see if this is something they'd like to support for all clients.

**Comment by jmthibault79** [comment]
Dunno if this is useful, but we have a brute-force script to delete all clusters in a google domain.
https://github.com/broadinstitute/firecloud-tools/tree/master/scripts/cleanup_clusters

**Comment by jmthibault79** [comment]
See also https://github.com/DataBiosphere/leonardo/issues/243

**Comment by bradtaylor** [comment]
Nobody tangible asking for this atm. Deemed a premature optimization
