### ISSUE TITLE
How many people are using Firefox? 

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/saturn-ui#974]

**Comment by zarsky-broad** [comment]
New Relic was never updated when we got the new domain name, so it hasn't been saving visits from app.terra.bio. I just updated that, so we should start having data now.

**Comment by zarsky-broad** [comment]
According to New Relic, in the last month app.terra.bio has been visited:
- 1.11K times in Chrome
- 27 times by Safari
- 12 times by Firefox
- 6 times by IE
