### ISSUE TITLE
Cannot see preview of WDL when importing from Dockstore

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#983]
When a user is importing a WDL from Dockstore, we are trying to display a preview of the WDL but the call to Dockstore fails, [see example on Terra prod](https://app.terra.bio/#import-tool/dockstore/github.com/DataBiosphere/topmed-workflows/u_of_Michigan_alignment_pipeline:1.30.0).  
In [FireCloud I can see a preview of the WDL](https://portal.firecloud.org/#import/dockstore/github.com/DataBiosphere/topmed-workflows/u_of_Michigan_alignment_pipeline:1.30.0).

FireCloud's call to Dockstore is to https://dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2Fgithub.com%2FDataBiosphere%2Ftopmed-workflows%2Fu_of_Michigan_alignment_pipeline/versions/1.30.0/WDL/descriptor and the remote address is 34.224.134.**183:8443**

Terra's call is to https://dockstore.org/api/ga4gh/v1/tools/%23workflow%2Fgithub.com%2FDataBiosphere%2Ftopmed-workflows%2Fu_of_Michigan_alignment_pipeline/versions/1.30.0/WDL/descriptor, and the remote address is 34.224.134.**183:443**

Could that missing 8 be the issue?

**Comment by zarsky-broad** [comment]
Fixed by #1160
